# Generated by protoc-gen-mojo from google/protobuf/any.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/any.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct Any(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Any` protobuf message."""

    var type_url: String
    """Field `type_url` (number 1)."""
    var value: List[Byte]
    """Field `value` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.type_url = String()
        self.value = List[Byte]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.type_url.byte_length() != 0:
            writer.string_field(1, self.type_url)
        if len(self.value) != 0:
            writer.bytes_field(2, Span(self.value))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type_url = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.bytes_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this Any with the configured type resolver.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the Any value cannot be resolved.
        """
        writer.any_value(self.type_url, self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this Any with the configured type resolver.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the Any value cannot be resolved.
        """
        var resolved = reader.any_value()
        self.type_url = resolved[0].copy()
        self.value = resolved[1].copy()


def any_pb_file_descriptor_proto() -> List[Byte]:
    """Serialized `FileDescriptorProto` for `google/protobuf/any.proto`."""
    var out: List[Byte] = [
        10, 25, 103, 111, 111, 103, 108, 101, 47, 112, 114, 111, 116, 111, 98, 117,
        102, 47, 97, 110, 121, 46, 112, 114, 111, 116, 111, 18, 15, 103, 111, 111,
        103, 108, 101, 46, 112, 114, 111, 116, 111, 98, 117, 102, 34, 54, 10, 3,
        65, 110, 121, 18, 25, 10, 8, 116, 121, 112, 101, 95, 117, 114, 108, 24,
        1, 32, 1, 40, 9, 82, 7, 116, 121, 112, 101, 85, 114, 108, 18, 20,
        10, 5, 118, 97, 108, 117, 101, 24, 2, 32, 1, 40, 12, 82, 5, 118,
        97, 108, 117, 101, 66, 118, 10, 19, 99, 111, 109, 46, 103, 111, 111, 103,
        108, 101, 46, 112, 114, 111, 116, 111, 98, 117, 102, 66, 8, 65, 110, 121,
        80, 114, 111, 116, 111, 80, 1, 90, 44, 103, 111, 111, 103, 108, 101, 46,
        103, 111, 108, 97, 110, 103, 46, 111, 114, 103, 47, 112, 114, 111, 116, 111,
        98, 117, 102, 47, 116, 121, 112, 101, 115, 47, 107, 110, 111, 119, 110, 47,
        97, 110, 121, 112, 98, 162, 2, 3, 71, 80, 66, 170, 2, 30, 71, 111,
        111, 103, 108, 101, 46, 80, 114, 111, 116, 111, 98, 117, 102, 46, 87, 101,
        108, 108, 75, 110, 111, 119, 110, 84, 121, 112, 101, 115, 98, 6, 112, 114,
        111, 116, 111, 51,
    ]
    return out^

def any_pb_proto_name() -> String:
    """Filename of `google/protobuf/any.proto` for gRPC reflection."""
    return String("google/protobuf/any.proto")

def any_pb_reflection_symbols() -> List[String]:
    """Fully-qualified symbols declared in `google/protobuf/any.proto`."""
    var symbols: List[String] = [
        String("google.protobuf.Any"),
    ]
    return symbols^
