# Generated by protoc-gen-mojo from google/protobuf/api.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/api.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)
from source_context_pb import SourceContext
from type_pb import Option, Syntax


struct Api(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Api` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var methods: List[Method]
    """Field `methods` (number 2, repeated)."""
    var options: List[Option]
    """Field `options` (number 3, repeated)."""
    var version: String
    """Field `version` (number 4)."""
    var source_context: Optional[SourceContext]
    """Field `source_context` (number 5)."""
    var mixins: List[Mixin]
    """Field `mixins` (number 6, repeated)."""
    var syntax: Syntax
    """Field `syntax` (number 7)."""
    var edition: String
    """Field `edition` (number 8)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.methods = List[Method]()
        self.options = List[Option]()
        self.version = String()
        self.source_context = None
        self.mixins = List[Mixin]()
        self.syntax = Syntax()
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        for v in self.methods:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.version.byte_length() != 0:
            writer.string_field(4, self.version)
        if self.source_context:
            var sub = WireWriter()
            self.source_context.value().encode_to(sub)
            writer.len_prefixed(5, Span(sub.buf))
        for v in self.mixins:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(6, Span(sub.buf))
        if self.syntax.value != 0:
            writer.int32(7, self.syntax.value)
        if self.edition.byte_length() != 0:
            writer.string_field(8, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Method()
                    m.merge_from(sub)
                    self.methods.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.version = reader.string_value()
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: SourceContext
                    if self.source_context:
                        m = self.source_context.take()
                    else:
                        m = SourceContext()
                    m.merge_from(sub)
                    self.source_context = m^
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Mixin()
                    m.merge_from(sub)
                    self.mixins.append(m^)
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = Syntax(value=reader.int32_value())
            elif field == 8:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if len(self.methods) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("methods", "methods")
            writer.begin_array()
            for item in self.methods:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.version.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("version", "version")
            writer.string_value(self.version)
        if self.source_context:
            writer.field("sourceContext", "source_context")
            writer.message_value(self.source_context.value())
        if len(self.mixins) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("mixins", "mixins")
            writer.begin_array()
            for item in self.mixins:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.syntax.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("syntax", "syntax")
            if self.syntax.value == 0:
                writer.string_value("SYNTAX_PROTO2")
            elif self.syntax.value == 1:
                writer.string_value("SYNTAX_PROTO3")
            elif self.syntax.value == 2:
                writer.string_value("SYNTAX_EDITIONS")
            else:
                writer.int32_value(self.syntax.value)
        if self.edition.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("edition", "edition")
            writer.string_value(self.edition)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        var seen_7 = False
        var seen_8 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "methods" or field_name == "methods":
                if seen_2:
                    raise Error("proto json: duplicate field methods")
                seen_2 = True
                if reader.read_null():
                    self.methods = List[Method]()
                else:
                    self.methods = List[Method]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.methods.append(reader.message_value[Method]())
            elif field_name == "options" or field_name == "options":
                if seen_3:
                    raise Error("proto json: duplicate field options")
                seen_3 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            elif field_name == "version" or field_name == "version":
                if seen_4:
                    raise Error("proto json: duplicate field version")
                seen_4 = True
                if reader.read_null():
                    self.version = String()
                else:
                    self.version = reader.string_value()
            elif field_name == "sourceContext" or field_name == "source_context":
                if seen_5:
                    raise Error("proto json: duplicate field sourceContext")
                seen_5 = True
                if reader.read_null():
                    self.source_context = None
                else:
                    self.source_context = reader.message_value[SourceContext]()
            elif field_name == "mixins" or field_name == "mixins":
                if seen_6:
                    raise Error("proto json: duplicate field mixins")
                seen_6 = True
                if reader.read_null():
                    self.mixins = List[Mixin]()
                else:
                    self.mixins = List[Mixin]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.mixins.append(reader.message_value[Mixin]())
            elif field_name == "syntax" or field_name == "syntax":
                if seen_7:
                    raise Error("proto json: duplicate field syntax")
                seen_7 = True
                if reader.read_null():
                    self.syntax = Syntax()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "SYNTAX_PROTO2":
                            self.syntax = Syntax(value=0)
                        elif enum_name.value() == "SYNTAX_PROTO3":
                            self.syntax = Syntax(value=1)
                        elif enum_name.value() == "SYNTAX_EDITIONS":
                            self.syntax = Syntax(value=2)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.syntax = Syntax(value=reader.int32_value())
            elif field_name == "edition" or field_name == "edition":
                if seen_8:
                    raise Error("proto json: duplicate field edition")
                seen_8 = True
                if reader.read_null():
                    self.edition = String()
                else:
                    self.edition = reader.string_value()
            else:
                reader.skip_unknown_value()


struct Method(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Method` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var request_type_url: String
    """Field `request_type_url` (number 2)."""
    var request_streaming: Bool
    """Field `request_streaming` (number 3)."""
    var response_type_url: String
    """Field `response_type_url` (number 4)."""
    var response_streaming: Bool
    """Field `response_streaming` (number 5)."""
    var options: List[Option]
    """Field `options` (number 6, repeated)."""
    var syntax: Syntax
    """Field `syntax` (number 7)."""
    var edition: String
    """Field `edition` (number 8)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.request_type_url = String()
        self.request_streaming = False
        self.response_type_url = String()
        self.response_streaming = False
        self.options = List[Option]()
        self.syntax = Syntax()
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.request_type_url.byte_length() != 0:
            writer.string_field(2, self.request_type_url)
        if self.request_streaming:
            writer.bool_field(3, self.request_streaming)
        if self.response_type_url.byte_length() != 0:
            writer.string_field(4, self.response_type_url)
        if self.response_streaming:
            writer.bool_field(5, self.response_streaming)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(6, Span(sub.buf))
        if self.syntax.value != 0:
            writer.int32(7, self.syntax.value)
        if self.edition.byte_length() != 0:
            writer.string_field(8, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.request_type_url = reader.string_value()
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.request_streaming = reader.bool_value()
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.response_type_url = reader.string_value()
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.response_streaming = reader.bool_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = Syntax(value=reader.int32_value())
            elif field == 8:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if self.request_type_url.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("requestTypeUrl", "request_type_url")
            writer.string_value(self.request_type_url)
        if self.request_streaming or writer.options.always_print_fields_with_no_presence:
            writer.field("requestStreaming", "request_streaming")
            writer.bool_value(self.request_streaming)
        if self.response_type_url.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("responseTypeUrl", "response_type_url")
            writer.string_value(self.response_type_url)
        if self.response_streaming or writer.options.always_print_fields_with_no_presence:
            writer.field("responseStreaming", "response_streaming")
            writer.bool_value(self.response_streaming)
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.syntax.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("syntax", "syntax")
            if self.syntax.value == 0:
                writer.string_value("SYNTAX_PROTO2")
            elif self.syntax.value == 1:
                writer.string_value("SYNTAX_PROTO3")
            elif self.syntax.value == 2:
                writer.string_value("SYNTAX_EDITIONS")
            else:
                writer.int32_value(self.syntax.value)
        if self.edition.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("edition", "edition")
            writer.string_value(self.edition)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        var seen_7 = False
        var seen_8 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "requestTypeUrl" or field_name == "request_type_url":
                if seen_2:
                    raise Error("proto json: duplicate field requestTypeUrl")
                seen_2 = True
                if reader.read_null():
                    self.request_type_url = String()
                else:
                    self.request_type_url = reader.string_value()
            elif field_name == "requestStreaming" or field_name == "request_streaming":
                if seen_3:
                    raise Error("proto json: duplicate field requestStreaming")
                seen_3 = True
                if reader.read_null():
                    self.request_streaming = False
                else:
                    self.request_streaming = reader.bool_value()
            elif field_name == "responseTypeUrl" or field_name == "response_type_url":
                if seen_4:
                    raise Error("proto json: duplicate field responseTypeUrl")
                seen_4 = True
                if reader.read_null():
                    self.response_type_url = String()
                else:
                    self.response_type_url = reader.string_value()
            elif field_name == "responseStreaming" or field_name == "response_streaming":
                if seen_5:
                    raise Error("proto json: duplicate field responseStreaming")
                seen_5 = True
                if reader.read_null():
                    self.response_streaming = False
                else:
                    self.response_streaming = reader.bool_value()
            elif field_name == "options" or field_name == "options":
                if seen_6:
                    raise Error("proto json: duplicate field options")
                seen_6 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            elif field_name == "syntax" or field_name == "syntax":
                if seen_7:
                    raise Error("proto json: duplicate field syntax")
                seen_7 = True
                if reader.read_null():
                    self.syntax = Syntax()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "SYNTAX_PROTO2":
                            self.syntax = Syntax(value=0)
                        elif enum_name.value() == "SYNTAX_PROTO3":
                            self.syntax = Syntax(value=1)
                        elif enum_name.value() == "SYNTAX_EDITIONS":
                            self.syntax = Syntax(value=2)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.syntax = Syntax(value=reader.int32_value())
            elif field_name == "edition" or field_name == "edition":
                if seen_8:
                    raise Error("proto json: duplicate field edition")
                seen_8 = True
                if reader.read_null():
                    self.edition = String()
                else:
                    self.edition = reader.string_value()
            else:
                reader.skip_unknown_value()


struct Mixin(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Mixin` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var root: String
    """Field `root` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.root = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.root.byte_length() != 0:
            writer.string_field(2, self.root)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.root = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if self.root.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("root", "root")
            writer.string_value(self.root)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "root" or field_name == "root":
                if seen_2:
                    raise Error("proto json: duplicate field root")
                seen_2 = True
                if reader.read_null():
                    self.root = String()
                else:
                    self.root = reader.string_value()
            else:
                reader.skip_unknown_value()
