# Generated by protoc-gen-mojo from google/protobuf/source_context.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/source_context.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct SourceContext(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `SourceContext` protobuf message."""

    var file_name: String
    """Field `file_name` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.file_name = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.file_name.byte_length() != 0:
            writer.string_field(1, self.file_name)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.file_name = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.file_name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fileName", "file_name")
            writer.string_value(self.file_name)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "fileName" or field_name == "file_name":
                if seen_1:
                    raise Error("proto json: duplicate field fileName")
                seen_1 = True
                if reader.read_null():
                    self.file_name = String()
                else:
                    self.file_name = reader.string_value()
            else:
                reader.skip_unknown_value()


def source_context_pb_file_descriptor_proto() -> List[Byte]:
    """Serialized `FileDescriptorProto` for `google/protobuf/source_context.proto`."""
    var out: List[Byte] = [
        10, 36, 103, 111, 111, 103, 108, 101, 47, 112, 114, 111, 116, 111, 98, 117,
        102, 47, 115, 111, 117, 114, 99, 101, 95, 99, 111, 110, 116, 101, 120, 116,
        46, 112, 114, 111, 116, 111, 18, 15, 103, 111, 111, 103, 108, 101, 46, 112,
        114, 111, 116, 111, 98, 117, 102, 34, 44, 10, 13, 83, 111, 117, 114, 99,
        101, 67, 111, 110, 116, 101, 120, 116, 18, 27, 10, 9, 102, 105, 108, 101,
        95, 110, 97, 109, 101, 24, 1, 32, 1, 40, 9, 82, 8, 102, 105, 108,
        101, 78, 97, 109, 101, 66, 138, 1, 10, 19, 99, 111, 109, 46, 103, 111,
        111, 103, 108, 101, 46, 112, 114, 111, 116, 111, 98, 117, 102, 66, 18, 83,
        111, 117, 114, 99, 101, 67, 111, 110, 116, 101, 120, 116, 80, 114, 111, 116,
        111, 80, 1, 90, 54, 103, 111, 111, 103, 108, 101, 46, 103, 111, 108, 97,
        110, 103, 46, 111, 114, 103, 47, 112, 114, 111, 116, 111, 98, 117, 102, 47,
        116, 121, 112, 101, 115, 47, 107, 110, 111, 119, 110, 47, 115, 111, 117, 114,
        99, 101, 99, 111, 110, 116, 101, 120, 116, 112, 98, 162, 2, 3, 71, 80,
        66, 170, 2, 30, 71, 111, 111, 103, 108, 101, 46, 80, 114, 111, 116, 111,
        98, 117, 102, 46, 87, 101, 108, 108, 75, 110, 111, 119, 110, 84, 121, 112,
        101, 115, 98, 6, 112, 114, 111, 116, 111, 51,
    ]
    return out^

def source_context_pb_proto_name() -> String:
    """Filename of `google/protobuf/source_context.proto` for gRPC reflection."""
    return String("google/protobuf/source_context.proto")

def source_context_pb_reflection_symbols() -> List[String]:
    """Fully-qualified symbols declared in `google/protobuf/source_context.proto`."""
    var symbols: List[String] = [
        String("google.protobuf.SourceContext"),
    ]
    return symbols^
