# Generated by protoc-gen-mojo from google/protobuf/struct.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/struct.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct NullValue:
    """Values of the `NullValue` protobuf enum (fields carry `Int32`)."""

    comptime NULL_VALUE = 0
    """`NULL_VALUE` = 0."""


struct Struct(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Struct` protobuf message."""

    var fields: Dict[String, Value]
    """Field `fields` (number 1, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.fields = Dict[String, Value]()
        self._unknown = List[Byte]()

    def __deinit__(deinit self):
        """Destroys the message (explicit: breaks the trait-synthesis cycle for recursive types)."""
        pass

    def __init__(out self, *, copy: Self):
        """Deep-copies another message.

        Args:
            copy: The message to copy from.
        """
        self.fields = copy.fields.copy()
        self._unknown = copy._unknown.copy()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for entry in self.fields.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            var vsub = WireWriter()
            entry.value.encode_to(vsub)
            sub.len_prefixed(2, Span(vsub.buf))
            writer.len_prefixed(1, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var entry_start = reader.pos
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Value = Value()
                    var entry_unknown = False
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1 and etag[1] == WIRE_LEN:
                            key = sub.string_value()
                        elif etag[0] == 2 and etag[1] == WIRE_LEN:
                            var msub = sub.sub_reader()
                            value.merge_from(msub)
                        else:
                            entry_unknown = True
                            sub.skip(etag[1])
                    if entry_unknown:
                        reader.pos = entry_start
                        reader.capture_field(field, wire_type, self._unknown)
                    else:
                        self.fields[key^] = value^
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this Struct as a JSON object.

        Args:
            writer: Destination JSON writer.
        """
        writer.begin_object()
        for entry in self.fields.items():
            writer.field(entry.key, entry.key)
            writer.message_value(entry.value)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this Struct from a JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not a valid JSON object.
        """
        self.fields = Dict[String, Value]()
        var seen_keys = List[String]()
        reader.begin_object()
        while True:
            var next_key = reader.next_field()
            if not next_key:
                break
            var key = next_key.value()
            for seen_key in seen_keys:
                if key == seen_key:
                    raise Error("proto json: duplicate Struct key")
            seen_keys.append(String(key))
            self.fields[key^] = reader.message_value[Value]()


struct Value(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Value` protobuf message."""

    var null_value: Int32
    """Field `null_value` (number 1)."""
    var number_value: Float64
    """Field `number_value` (number 2)."""
    var string_value: String
    """Field `string_value` (number 3)."""
    var bool_value: Bool
    """Field `bool_value` (number 4)."""
    var struct_value: Optional[Struct]
    """Field `struct_value` (number 5)."""
    var list_value: Optional[ListValue]
    """Field `list_value` (number 6)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""
    var kind_case: Int
    """Active member of oneof `kind`: 0 when unset, else the set field number."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.null_value = 0
        self.number_value = 0.0
        self.string_value = String()
        self.bool_value = False
        self.struct_value = None
        self.list_value = None
        self._unknown = List[Byte]()
        self.kind_case = 0

    def __deinit__(deinit self):
        """Destroys the message (explicit: breaks the trait-synthesis cycle for recursive types)."""
        pass

    def __init__(out self, *, copy: Self):
        """Deep-copies another message.

        Args:
            copy: The message to copy from.
        """
        self.null_value = copy.null_value
        self.number_value = copy.number_value
        self.string_value = copy.string_value.copy()
        self.bool_value = copy.bool_value
        self.struct_value = copy.struct_value.copy()
        self.list_value = copy.list_value.copy()
        self.kind_case = copy.kind_case
        self._unknown = copy._unknown.copy()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.kind_case == 1:
            writer.int32(1, self.null_value)
        elif self.kind_case == 2:
            writer.double_field(2, self.number_value)
        elif self.kind_case == 3:
            writer.string_field(3, self.string_value)
        elif self.kind_case == 4:
            writer.bool_field(4, self.bool_value)
        elif self.kind_case == 5:
            if self.struct_value:
                var sub = WireWriter()
                self.struct_value.value().encode_to(sub)
                writer.len_prefixed(5, Span(sub.buf))
        elif self.kind_case == 6:
            if self.list_value:
                var sub = WireWriter()
                self.list_value.value().encode_to(sub)
                writer.len_prefixed(6, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.null_value = reader.int32_value()
                    self.kind_case = 1
                    self.number_value = 0.0
                    self.string_value = String()
                    self.bool_value = False
                    self.struct_value = None
                    self.list_value = None
            elif field == 2:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.number_value = reader.double_value()
                    self.kind_case = 2
                    self.null_value = 0
                    self.string_value = String()
                    self.bool_value = False
                    self.struct_value = None
                    self.list_value = None
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.string_value = reader.string_value()
                    self.kind_case = 3
                    self.null_value = 0
                    self.number_value = 0.0
                    self.bool_value = False
                    self.struct_value = None
                    self.list_value = None
            elif field == 4:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.bool_value = reader.bool_value()
                    self.kind_case = 4
                    self.null_value = 0
                    self.number_value = 0.0
                    self.string_value = String()
                    self.struct_value = None
                    self.list_value = None
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Struct
                    if self.kind_case == 5 and self.struct_value:
                        m = self.struct_value.take()
                    else:
                        m = Struct()
                    m.merge_from(sub)
                    self.struct_value = m^
                    self.kind_case = 5
                    self.null_value = 0
                    self.number_value = 0.0
                    self.string_value = String()
                    self.bool_value = False
                    self.list_value = None
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: ListValue
                    if self.kind_case == 6 and self.list_value:
                        m = self.list_value.take()
                    else:
                        m = ListValue()
                    m.merge_from(sub)
                    self.list_value = m^
                    self.kind_case = 6
                    self.null_value = 0
                    self.number_value = 0.0
                    self.string_value = String()
                    self.bool_value = False
                    self.struct_value = None
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this Value as its selected JSON value.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a number is not finite or a message is absent.
        """
        if self.kind_case == 0 or self.kind_case == 1:
            writer.null_value()
        elif self.kind_case == 2:
            writer.finite_float64_value(self.number_value)
        elif self.kind_case == 3:
            writer.string_value(self.string_value)
        elif self.kind_case == 4:
            writer.bool_value(self.bool_value)
        elif self.kind_case == 5 and self.struct_value:
            writer.message_value(self.struct_value.value())
        elif self.kind_case == 6 and self.list_value:
            writer.message_value(self.list_value.value())
        else:
            raise Error("proto json: Value message is absent")

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads the next JSON value into this Value.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not a valid JSON value.
        """
        var value_kind = reader.next_value_kind()
        self.null_value = 0
        self.number_value = 0.0
        self.string_value = String()
        self.bool_value = False
        self.struct_value = None
        self.list_value = None
        if value_kind == 0:
            _ = reader.read_null()
            self.kind_case = 1
        elif value_kind == 1:
            self.string_value = reader.string_value()
            self.kind_case = 3
        elif value_kind == 2:
            self.number_value = reader.float64_value()
            self.kind_case = 2
        elif value_kind == 3:
            self.bool_value = reader.bool_value()
            self.kind_case = 4
        elif value_kind == 4:
            self.struct_value = reader.same_value_message[Struct]()
            self.kind_case = 5
        else:
            self.list_value = reader.same_value_message[ListValue]()
            self.kind_case = 6


struct ListValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `ListValue` protobuf message."""

    var values: List[Value]
    """Field `values` (number 1, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.values = List[Value]()
        self._unknown = List[Byte]()

    def __deinit__(deinit self):
        """Destroys the message (explicit: breaks the trait-synthesis cycle for recursive types)."""
        pass

    def __init__(out self, *, copy: Self):
        """Deep-copies another message.

        Args:
            copy: The message to copy from.
        """
        self.values = copy.values.copy()
        self._unknown = copy._unknown.copy()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for v in self.values:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Value()
                    m.merge_from(sub)
                    self.values.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this ListValue as a JSON array.

        Args:
            writer: Destination JSON writer.
        """
        writer.begin_array()
        for item in self.values:
            writer.array_item()
            writer.message_value(item)
        writer.end_array()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this ListValue from a JSON array.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not a valid JSON array.
        """
        self.values = List[Value]()
        reader.begin_value_array()
        while reader.next_array_item():
            self.values.append(reader.message_value[Value]())
