# Generated by protoc-gen-mojo from google/protobuf/timestamp.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/timestamp.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct Timestamp(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Timestamp` protobuf message."""

    var seconds: Int64
    """Field `seconds` (number 1)."""
    var nanos: Int32
    """Field `nanos` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.seconds = 0
        self.nanos = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.seconds != 0:
            writer.int64(1, self.seconds)
        if self.nanos != 0:
            writer.int32(2, self.nanos)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.seconds = reader.int64_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.nanos = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this Timestamp using its RFC 3339 mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the Timestamp is outside its valid range.
        """
        writer.timestamp_value(self.seconds, self.nanos)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this Timestamp from its RFC 3339 mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the Timestamp is malformed or out of range.
        """
        var value = reader.timestamp_value()
        self.seconds = value[0]
        self.nanos = value[1]
