# Generated by protoc-gen-mojo from google/protobuf/type.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/type.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from any_pb import Any
from source_context_pb import SourceContext


struct Syntax:
    """Values of the `Syntax` protobuf enum (fields carry `Int32`)."""

    comptime SYNTAX_PROTO2 = 0
    """`SYNTAX_PROTO2` = 0."""
    comptime SYNTAX_PROTO3 = 1
    """`SYNTAX_PROTO3` = 1."""
    comptime SYNTAX_EDITIONS = 2
    """`SYNTAX_EDITIONS` = 2."""


struct Type(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Type` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var fields: List[Field]
    """Field `fields` (number 2, repeated)."""
    var oneofs: List[String]
    """Field `oneofs` (number 3, repeated)."""
    var options: List[Option]
    """Field `options` (number 4, repeated)."""
    var source_context: Optional[SourceContext]
    """Field `source_context` (number 5)."""
    var syntax: Int32
    """Field `syntax` (number 6)."""
    var edition: String
    """Field `edition` (number 7)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.fields = List[Field]()
        self.oneofs = List[String]()
        self.options = List[Option]()
        self.source_context = None
        self.syntax = 0
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        for v in self.fields:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.oneofs:
            writer.string_field(3, v)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        if self.source_context:
            var sub = WireWriter()
            self.source_context.value().encode_to(sub)
            writer.len_prefixed(5, Span(sub.buf))
        if self.syntax != 0:
            writer.int32(6, self.syntax)
        if self.edition.byte_length() != 0:
            writer.string_field(7, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Field()
                    m.merge_from(sub)
                    self.fields.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.oneofs.append(reader.string_value())
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: SourceContext
                    if self.source_context:
                        m = self.source_context.take()
                    else:
                        m = SourceContext()
                    m.merge_from(sub)
                    self.source_context = m^
            elif field == 6:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = reader.int32_value()
            elif field == 7:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Field_Kind:
    """Values of the `Kind` protobuf enum (fields carry `Int32`)."""

    comptime TYPE_UNKNOWN = 0
    """`TYPE_UNKNOWN` = 0."""
    comptime TYPE_DOUBLE = 1
    """`TYPE_DOUBLE` = 1."""
    comptime TYPE_FLOAT = 2
    """`TYPE_FLOAT` = 2."""
    comptime TYPE_INT64 = 3
    """`TYPE_INT64` = 3."""
    comptime TYPE_UINT64 = 4
    """`TYPE_UINT64` = 4."""
    comptime TYPE_INT32 = 5
    """`TYPE_INT32` = 5."""
    comptime TYPE_FIXED64 = 6
    """`TYPE_FIXED64` = 6."""
    comptime TYPE_FIXED32 = 7
    """`TYPE_FIXED32` = 7."""
    comptime TYPE_BOOL = 8
    """`TYPE_BOOL` = 8."""
    comptime TYPE_STRING = 9
    """`TYPE_STRING` = 9."""
    comptime TYPE_GROUP = 10
    """`TYPE_GROUP` = 10."""
    comptime TYPE_MESSAGE = 11
    """`TYPE_MESSAGE` = 11."""
    comptime TYPE_BYTES = 12
    """`TYPE_BYTES` = 12."""
    comptime TYPE_UINT32 = 13
    """`TYPE_UINT32` = 13."""
    comptime TYPE_ENUM = 14
    """`TYPE_ENUM` = 14."""
    comptime TYPE_SFIXED32 = 15
    """`TYPE_SFIXED32` = 15."""
    comptime TYPE_SFIXED64 = 16
    """`TYPE_SFIXED64` = 16."""
    comptime TYPE_SINT32 = 17
    """`TYPE_SINT32` = 17."""
    comptime TYPE_SINT64 = 18
    """`TYPE_SINT64` = 18."""


struct Field_Cardinality:
    """Values of the `Cardinality` protobuf enum (fields carry `Int32`)."""

    comptime CARDINALITY_UNKNOWN = 0
    """`CARDINALITY_UNKNOWN` = 0."""
    comptime CARDINALITY_OPTIONAL = 1
    """`CARDINALITY_OPTIONAL` = 1."""
    comptime CARDINALITY_REQUIRED = 2
    """`CARDINALITY_REQUIRED` = 2."""
    comptime CARDINALITY_REPEATED = 3
    """`CARDINALITY_REPEATED` = 3."""


struct Field(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Field` protobuf message."""

    var kind: Int32
    """Field `kind` (number 1)."""
    var cardinality: Int32
    """Field `cardinality` (number 2)."""
    var number: Int32
    """Field `number` (number 3)."""
    var name: String
    """Field `name` (number 4)."""
    var type_url: String
    """Field `type_url` (number 6)."""
    var oneof_index: Int32
    """Field `oneof_index` (number 7)."""
    var packed: Bool
    """Field `packed` (number 8)."""
    var options: List[Option]
    """Field `options` (number 9, repeated)."""
    var json_name: String
    """Field `json_name` (number 10)."""
    var default_value: String
    """Field `default_value` (number 11)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.kind = 0
        self.cardinality = 0
        self.number = 0
        self.name = String()
        self.type_url = String()
        self.oneof_index = 0
        self.packed = False
        self.options = List[Option]()
        self.json_name = String()
        self.default_value = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.kind != 0:
            writer.int32(1, self.kind)
        if self.cardinality != 0:
            writer.int32(2, self.cardinality)
        if self.number != 0:
            writer.int32(3, self.number)
        if self.name.byte_length() != 0:
            writer.string_field(4, self.name)
        if self.type_url.byte_length() != 0:
            writer.string_field(6, self.type_url)
        if self.oneof_index != 0:
            writer.int32(7, self.oneof_index)
        if self.packed:
            writer.bool_field(8, self.packed)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(9, Span(sub.buf))
        if self.json_name.byte_length() != 0:
            writer.string_field(10, self.json_name)
        if self.default_value.byte_length() != 0:
            writer.string_field(11, self.default_value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.kind = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.cardinality = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.number = reader.int32_value()
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type_url = reader.string_value()
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.oneof_index = reader.int32_value()
            elif field == 8:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.packed = reader.bool_value()
            elif field == 9:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 10:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.json_name = reader.string_value()
            elif field == 11:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.default_value = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Enum(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Enum` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var enumvalue: List[EnumValue]
    """Field `enumvalue` (number 2, repeated)."""
    var options: List[Option]
    """Field `options` (number 3, repeated)."""
    var source_context: Optional[SourceContext]
    """Field `source_context` (number 4)."""
    var syntax: Int32
    """Field `syntax` (number 5)."""
    var edition: String
    """Field `edition` (number 6)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.enumvalue = List[EnumValue]()
        self.options = List[Option]()
        self.source_context = None
        self.syntax = 0
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        for v in self.enumvalue:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.source_context:
            var sub = WireWriter()
            self.source_context.value().encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        if self.syntax != 0:
            writer.int32(5, self.syntax)
        if self.edition.byte_length() != 0:
            writer.string_field(6, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = EnumValue()
                    m.merge_from(sub)
                    self.enumvalue.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: SourceContext
                    if self.source_context:
                        m = self.source_context.take()
                    else:
                        m = SourceContext()
                    m.merge_from(sub)
                    self.source_context = m^
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = reader.int32_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct EnumValue(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `EnumValue` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var number: Int32
    """Field `number` (number 2)."""
    var options: List[Option]
    """Field `options` (number 3, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.number = 0
        self.options = List[Option]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.number != 0:
            writer.int32(2, self.number)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.number = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Option(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Option` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var value: Optional[Any]
    """Field `value` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.value = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.value:
            var sub = WireWriter()
            self.value.value().encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Any
                    if self.value:
                        m = self.value.take()
                    else:
                        m = Any()
                    m.merge_from(sub)
                    self.value = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)
