# Generated by protoc-gen-mojo from google/protobuf/type.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/type.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)
from any_pb import Any
from source_context_pb import SourceContext


struct Syntax(Copyable, ImplicitlyCopyable, Movable, Equatable):
    """Proto3 open enum `Syntax`. Unknown numeric values are preserved."""

    var value: Int32
    """The wire number, including values not named in the .proto."""

    comptime SYNTAX_PROTO2: Int32 = 0
    """`SYNTAX_PROTO2` = 0."""
    comptime SYNTAX_PROTO3: Int32 = 1
    """`SYNTAX_PROTO3` = 1."""
    comptime SYNTAX_EDITIONS: Int32 = 2
    """`SYNTAX_EDITIONS` = 2."""

    def __init__(out self, value: Int32 = 0):
        """Wraps a proto3 enum number, including unknown values.

        Args:
            value: The wire number. Defaults to 0 (the unspecified value).
        """
        self.value = value

    def __eq__(self, other: Self) -> Bool:
        """Compares two enum wrappers by wire number."""
        return self.value == other.value

    def name(self) -> Optional[String]:
        """Returns the first declared name for this number, or None if unknown."""
        if self.value == 0:
            return String("SYNTAX_PROTO2")
        elif self.value == 1:
            return String("SYNTAX_PROTO3")
        elif self.value == 2:
            return String("SYNTAX_EDITIONS")
        return None

    @staticmethod
    def from_name(name: StringSpan) -> Optional[Self]:
        """Looks up a declared name. Unknown names return None."""
        if name == "SYNTAX_PROTO2":
            return Self(value=0)
        elif name == "SYNTAX_PROTO3":
            return Self(value=1)
        elif name == "SYNTAX_EDITIONS":
            return Self(value=2)
        return None


struct Type(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Type` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var fields: List[Field]
    """Field `fields` (number 2, repeated)."""
    var oneofs: List[String]
    """Field `oneofs` (number 3, repeated)."""
    var options: List[Option]
    """Field `options` (number 4, repeated)."""
    var source_context: Optional[SourceContext]
    """Field `source_context` (number 5)."""
    var syntax: Syntax
    """Field `syntax` (number 6)."""
    var edition: String
    """Field `edition` (number 7)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.fields = List[Field]()
        self.oneofs = List[String]()
        self.options = List[Option]()
        self.source_context = None
        self.syntax = Syntax()
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        for v in self.fields:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.oneofs:
            writer.string_field(3, v)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        if self.source_context:
            var sub = WireWriter()
            self.source_context.value().encode_to(sub)
            writer.len_prefixed(5, Span(sub.buf))
        if self.syntax.value != 0:
            writer.int32(6, self.syntax.value)
        if self.edition.byte_length() != 0:
            writer.string_field(7, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Field()
                    m.merge_from(sub)
                    self.fields.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.oneofs.append(reader.string_value())
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: SourceContext
                    if self.source_context:
                        m = self.source_context.take()
                    else:
                        m = SourceContext()
                    m.merge_from(sub)
                    self.source_context = m^
            elif field == 6:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = Syntax(value=reader.int32_value())
            elif field == 7:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if len(self.fields) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fields", "fields")
            writer.begin_array()
            for item in self.fields:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if len(self.oneofs) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("oneofs", "oneofs")
            writer.begin_array()
            for item in self.oneofs:
                writer.array_item()
                writer.string_value(item)
            writer.end_array()
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.source_context:
            writer.field("sourceContext", "source_context")
            writer.message_value(self.source_context.value())
        if self.syntax.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("syntax", "syntax")
            if self.syntax.value == 0:
                writer.string_value("SYNTAX_PROTO2")
            elif self.syntax.value == 1:
                writer.string_value("SYNTAX_PROTO3")
            elif self.syntax.value == 2:
                writer.string_value("SYNTAX_EDITIONS")
            else:
                writer.int32_value(self.syntax.value)
        if self.edition.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("edition", "edition")
            writer.string_value(self.edition)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        var seen_7 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "fields" or field_name == "fields":
                if seen_2:
                    raise Error("proto json: duplicate field fields")
                seen_2 = True
                if reader.read_null():
                    self.fields = List[Field]()
                else:
                    self.fields = List[Field]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.fields.append(reader.message_value[Field]())
            elif field_name == "oneofs" or field_name == "oneofs":
                if seen_3:
                    raise Error("proto json: duplicate field oneofs")
                seen_3 = True
                if reader.read_null():
                    self.oneofs = List[String]()
                else:
                    self.oneofs = List[String]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.oneofs.append(reader.string_value())
            elif field_name == "options" or field_name == "options":
                if seen_4:
                    raise Error("proto json: duplicate field options")
                seen_4 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            elif field_name == "sourceContext" or field_name == "source_context":
                if seen_5:
                    raise Error("proto json: duplicate field sourceContext")
                seen_5 = True
                if reader.read_null():
                    self.source_context = None
                else:
                    self.source_context = reader.message_value[SourceContext]()
            elif field_name == "syntax" or field_name == "syntax":
                if seen_6:
                    raise Error("proto json: duplicate field syntax")
                seen_6 = True
                if reader.read_null():
                    self.syntax = Syntax()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "SYNTAX_PROTO2":
                            self.syntax = Syntax(value=0)
                        elif enum_name.value() == "SYNTAX_PROTO3":
                            self.syntax = Syntax(value=1)
                        elif enum_name.value() == "SYNTAX_EDITIONS":
                            self.syntax = Syntax(value=2)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.syntax = Syntax(value=reader.int32_value())
            elif field_name == "edition" or field_name == "edition":
                if seen_7:
                    raise Error("proto json: duplicate field edition")
                seen_7 = True
                if reader.read_null():
                    self.edition = String()
                else:
                    self.edition = reader.string_value()
            else:
                reader.skip_unknown_value()


struct Field_Kind(Copyable, ImplicitlyCopyable, Movable, Equatable):
    """Proto3 open enum `Kind`. Unknown numeric values are preserved."""

    var value: Int32
    """The wire number, including values not named in the .proto."""

    comptime TYPE_UNKNOWN: Int32 = 0
    """`TYPE_UNKNOWN` = 0."""
    comptime TYPE_DOUBLE: Int32 = 1
    """`TYPE_DOUBLE` = 1."""
    comptime TYPE_FLOAT: Int32 = 2
    """`TYPE_FLOAT` = 2."""
    comptime TYPE_INT64: Int32 = 3
    """`TYPE_INT64` = 3."""
    comptime TYPE_UINT64: Int32 = 4
    """`TYPE_UINT64` = 4."""
    comptime TYPE_INT32: Int32 = 5
    """`TYPE_INT32` = 5."""
    comptime TYPE_FIXED64: Int32 = 6
    """`TYPE_FIXED64` = 6."""
    comptime TYPE_FIXED32: Int32 = 7
    """`TYPE_FIXED32` = 7."""
    comptime TYPE_BOOL: Int32 = 8
    """`TYPE_BOOL` = 8."""
    comptime TYPE_STRING: Int32 = 9
    """`TYPE_STRING` = 9."""
    comptime TYPE_GROUP: Int32 = 10
    """`TYPE_GROUP` = 10."""
    comptime TYPE_MESSAGE: Int32 = 11
    """`TYPE_MESSAGE` = 11."""
    comptime TYPE_BYTES: Int32 = 12
    """`TYPE_BYTES` = 12."""
    comptime TYPE_UINT32: Int32 = 13
    """`TYPE_UINT32` = 13."""
    comptime TYPE_ENUM: Int32 = 14
    """`TYPE_ENUM` = 14."""
    comptime TYPE_SFIXED32: Int32 = 15
    """`TYPE_SFIXED32` = 15."""
    comptime TYPE_SFIXED64: Int32 = 16
    """`TYPE_SFIXED64` = 16."""
    comptime TYPE_SINT32: Int32 = 17
    """`TYPE_SINT32` = 17."""
    comptime TYPE_SINT64: Int32 = 18
    """`TYPE_SINT64` = 18."""

    def __init__(out self, value: Int32 = 0):
        """Wraps a proto3 enum number, including unknown values.

        Args:
            value: The wire number. Defaults to 0 (the unspecified value).
        """
        self.value = value

    def __eq__(self, other: Self) -> Bool:
        """Compares two enum wrappers by wire number."""
        return self.value == other.value

    def name(self) -> Optional[String]:
        """Returns the first declared name for this number, or None if unknown."""
        if self.value == 0:
            return String("TYPE_UNKNOWN")
        elif self.value == 1:
            return String("TYPE_DOUBLE")
        elif self.value == 2:
            return String("TYPE_FLOAT")
        elif self.value == 3:
            return String("TYPE_INT64")
        elif self.value == 4:
            return String("TYPE_UINT64")
        elif self.value == 5:
            return String("TYPE_INT32")
        elif self.value == 6:
            return String("TYPE_FIXED64")
        elif self.value == 7:
            return String("TYPE_FIXED32")
        elif self.value == 8:
            return String("TYPE_BOOL")
        elif self.value == 9:
            return String("TYPE_STRING")
        elif self.value == 10:
            return String("TYPE_GROUP")
        elif self.value == 11:
            return String("TYPE_MESSAGE")
        elif self.value == 12:
            return String("TYPE_BYTES")
        elif self.value == 13:
            return String("TYPE_UINT32")
        elif self.value == 14:
            return String("TYPE_ENUM")
        elif self.value == 15:
            return String("TYPE_SFIXED32")
        elif self.value == 16:
            return String("TYPE_SFIXED64")
        elif self.value == 17:
            return String("TYPE_SINT32")
        elif self.value == 18:
            return String("TYPE_SINT64")
        return None

    @staticmethod
    def from_name(name: StringSpan) -> Optional[Self]:
        """Looks up a declared name. Unknown names return None."""
        if name == "TYPE_UNKNOWN":
            return Self(value=0)
        elif name == "TYPE_DOUBLE":
            return Self(value=1)
        elif name == "TYPE_FLOAT":
            return Self(value=2)
        elif name == "TYPE_INT64":
            return Self(value=3)
        elif name == "TYPE_UINT64":
            return Self(value=4)
        elif name == "TYPE_INT32":
            return Self(value=5)
        elif name == "TYPE_FIXED64":
            return Self(value=6)
        elif name == "TYPE_FIXED32":
            return Self(value=7)
        elif name == "TYPE_BOOL":
            return Self(value=8)
        elif name == "TYPE_STRING":
            return Self(value=9)
        elif name == "TYPE_GROUP":
            return Self(value=10)
        elif name == "TYPE_MESSAGE":
            return Self(value=11)
        elif name == "TYPE_BYTES":
            return Self(value=12)
        elif name == "TYPE_UINT32":
            return Self(value=13)
        elif name == "TYPE_ENUM":
            return Self(value=14)
        elif name == "TYPE_SFIXED32":
            return Self(value=15)
        elif name == "TYPE_SFIXED64":
            return Self(value=16)
        elif name == "TYPE_SINT32":
            return Self(value=17)
        elif name == "TYPE_SINT64":
            return Self(value=18)
        return None


struct Field_Cardinality(Copyable, ImplicitlyCopyable, Movable, Equatable):
    """Proto3 open enum `Cardinality`. Unknown numeric values are preserved."""

    var value: Int32
    """The wire number, including values not named in the .proto."""

    comptime CARDINALITY_UNKNOWN: Int32 = 0
    """`CARDINALITY_UNKNOWN` = 0."""
    comptime CARDINALITY_OPTIONAL: Int32 = 1
    """`CARDINALITY_OPTIONAL` = 1."""
    comptime CARDINALITY_REQUIRED: Int32 = 2
    """`CARDINALITY_REQUIRED` = 2."""
    comptime CARDINALITY_REPEATED: Int32 = 3
    """`CARDINALITY_REPEATED` = 3."""

    def __init__(out self, value: Int32 = 0):
        """Wraps a proto3 enum number, including unknown values.

        Args:
            value: The wire number. Defaults to 0 (the unspecified value).
        """
        self.value = value

    def __eq__(self, other: Self) -> Bool:
        """Compares two enum wrappers by wire number."""
        return self.value == other.value

    def name(self) -> Optional[String]:
        """Returns the first declared name for this number, or None if unknown."""
        if self.value == 0:
            return String("CARDINALITY_UNKNOWN")
        elif self.value == 1:
            return String("CARDINALITY_OPTIONAL")
        elif self.value == 2:
            return String("CARDINALITY_REQUIRED")
        elif self.value == 3:
            return String("CARDINALITY_REPEATED")
        return None

    @staticmethod
    def from_name(name: StringSpan) -> Optional[Self]:
        """Looks up a declared name. Unknown names return None."""
        if name == "CARDINALITY_UNKNOWN":
            return Self(value=0)
        elif name == "CARDINALITY_OPTIONAL":
            return Self(value=1)
        elif name == "CARDINALITY_REQUIRED":
            return Self(value=2)
        elif name == "CARDINALITY_REPEATED":
            return Self(value=3)
        return None


struct Field(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Field` protobuf message."""

    var kind: Field_Kind
    """Field `kind` (number 1)."""
    var cardinality: Field_Cardinality
    """Field `cardinality` (number 2)."""
    var number: Int32
    """Field `number` (number 3)."""
    var name: String
    """Field `name` (number 4)."""
    var type_url: String
    """Field `type_url` (number 6)."""
    var oneof_index: Int32
    """Field `oneof_index` (number 7)."""
    var packed: Bool
    """Field `packed` (number 8)."""
    var options: List[Option]
    """Field `options` (number 9, repeated)."""
    var json_name: String
    """Field `json_name` (number 10)."""
    var default_value: String
    """Field `default_value` (number 11)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.kind = Field_Kind()
        self.cardinality = Field_Cardinality()
        self.number = 0
        self.name = String()
        self.type_url = String()
        self.oneof_index = 0
        self.packed = False
        self.options = List[Option]()
        self.json_name = String()
        self.default_value = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.kind.value != 0:
            writer.int32(1, self.kind.value)
        if self.cardinality.value != 0:
            writer.int32(2, self.cardinality.value)
        if self.number != 0:
            writer.int32(3, self.number)
        if self.name.byte_length() != 0:
            writer.string_field(4, self.name)
        if self.type_url.byte_length() != 0:
            writer.string_field(6, self.type_url)
        if self.oneof_index != 0:
            writer.int32(7, self.oneof_index)
        if self.packed:
            writer.bool_field(8, self.packed)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(9, Span(sub.buf))
        if self.json_name.byte_length() != 0:
            writer.string_field(10, self.json_name)
        if self.default_value.byte_length() != 0:
            writer.string_field(11, self.default_value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.kind = Field_Kind(value=reader.int32_value())
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.cardinality = Field_Cardinality(value=reader.int32_value())
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.number = reader.int32_value()
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type_url = reader.string_value()
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.oneof_index = reader.int32_value()
            elif field == 8:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.packed = reader.bool_value()
            elif field == 9:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 10:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.json_name = reader.string_value()
            elif field == 11:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.default_value = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.kind.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("kind", "kind")
            if self.kind.value == 0:
                writer.string_value("TYPE_UNKNOWN")
            elif self.kind.value == 1:
                writer.string_value("TYPE_DOUBLE")
            elif self.kind.value == 2:
                writer.string_value("TYPE_FLOAT")
            elif self.kind.value == 3:
                writer.string_value("TYPE_INT64")
            elif self.kind.value == 4:
                writer.string_value("TYPE_UINT64")
            elif self.kind.value == 5:
                writer.string_value("TYPE_INT32")
            elif self.kind.value == 6:
                writer.string_value("TYPE_FIXED64")
            elif self.kind.value == 7:
                writer.string_value("TYPE_FIXED32")
            elif self.kind.value == 8:
                writer.string_value("TYPE_BOOL")
            elif self.kind.value == 9:
                writer.string_value("TYPE_STRING")
            elif self.kind.value == 10:
                writer.string_value("TYPE_GROUP")
            elif self.kind.value == 11:
                writer.string_value("TYPE_MESSAGE")
            elif self.kind.value == 12:
                writer.string_value("TYPE_BYTES")
            elif self.kind.value == 13:
                writer.string_value("TYPE_UINT32")
            elif self.kind.value == 14:
                writer.string_value("TYPE_ENUM")
            elif self.kind.value == 15:
                writer.string_value("TYPE_SFIXED32")
            elif self.kind.value == 16:
                writer.string_value("TYPE_SFIXED64")
            elif self.kind.value == 17:
                writer.string_value("TYPE_SINT32")
            elif self.kind.value == 18:
                writer.string_value("TYPE_SINT64")
            else:
                writer.int32_value(self.kind.value)
        if self.cardinality.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("cardinality", "cardinality")
            if self.cardinality.value == 0:
                writer.string_value("CARDINALITY_UNKNOWN")
            elif self.cardinality.value == 1:
                writer.string_value("CARDINALITY_OPTIONAL")
            elif self.cardinality.value == 2:
                writer.string_value("CARDINALITY_REQUIRED")
            elif self.cardinality.value == 3:
                writer.string_value("CARDINALITY_REPEATED")
            else:
                writer.int32_value(self.cardinality.value)
        if self.number != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("number", "number")
            writer.int32_value(self.number)
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if self.type_url.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("typeUrl", "type_url")
            writer.string_value(self.type_url)
        if self.oneof_index != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("oneofIndex", "oneof_index")
            writer.int32_value(self.oneof_index)
        if self.packed or writer.options.always_print_fields_with_no_presence:
            writer.field("packed", "packed")
            writer.bool_value(self.packed)
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.json_name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("jsonName", "json_name")
            writer.string_value(self.json_name)
        if self.default_value.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("defaultValue", "default_value")
            writer.string_value(self.default_value)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_6 = False
        var seen_7 = False
        var seen_8 = False
        var seen_9 = False
        var seen_10 = False
        var seen_11 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "kind" or field_name == "kind":
                if seen_1:
                    raise Error("proto json: duplicate field kind")
                seen_1 = True
                if reader.read_null():
                    self.kind = Field_Kind()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "TYPE_UNKNOWN":
                            self.kind = Field_Kind(value=0)
                        elif enum_name.value() == "TYPE_DOUBLE":
                            self.kind = Field_Kind(value=1)
                        elif enum_name.value() == "TYPE_FLOAT":
                            self.kind = Field_Kind(value=2)
                        elif enum_name.value() == "TYPE_INT64":
                            self.kind = Field_Kind(value=3)
                        elif enum_name.value() == "TYPE_UINT64":
                            self.kind = Field_Kind(value=4)
                        elif enum_name.value() == "TYPE_INT32":
                            self.kind = Field_Kind(value=5)
                        elif enum_name.value() == "TYPE_FIXED64":
                            self.kind = Field_Kind(value=6)
                        elif enum_name.value() == "TYPE_FIXED32":
                            self.kind = Field_Kind(value=7)
                        elif enum_name.value() == "TYPE_BOOL":
                            self.kind = Field_Kind(value=8)
                        elif enum_name.value() == "TYPE_STRING":
                            self.kind = Field_Kind(value=9)
                        elif enum_name.value() == "TYPE_GROUP":
                            self.kind = Field_Kind(value=10)
                        elif enum_name.value() == "TYPE_MESSAGE":
                            self.kind = Field_Kind(value=11)
                        elif enum_name.value() == "TYPE_BYTES":
                            self.kind = Field_Kind(value=12)
                        elif enum_name.value() == "TYPE_UINT32":
                            self.kind = Field_Kind(value=13)
                        elif enum_name.value() == "TYPE_ENUM":
                            self.kind = Field_Kind(value=14)
                        elif enum_name.value() == "TYPE_SFIXED32":
                            self.kind = Field_Kind(value=15)
                        elif enum_name.value() == "TYPE_SFIXED64":
                            self.kind = Field_Kind(value=16)
                        elif enum_name.value() == "TYPE_SINT32":
                            self.kind = Field_Kind(value=17)
                        elif enum_name.value() == "TYPE_SINT64":
                            self.kind = Field_Kind(value=18)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.kind = Field_Kind(value=reader.int32_value())
            elif field_name == "cardinality" or field_name == "cardinality":
                if seen_2:
                    raise Error("proto json: duplicate field cardinality")
                seen_2 = True
                if reader.read_null():
                    self.cardinality = Field_Cardinality()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "CARDINALITY_UNKNOWN":
                            self.cardinality = Field_Cardinality(value=0)
                        elif enum_name.value() == "CARDINALITY_OPTIONAL":
                            self.cardinality = Field_Cardinality(value=1)
                        elif enum_name.value() == "CARDINALITY_REQUIRED":
                            self.cardinality = Field_Cardinality(value=2)
                        elif enum_name.value() == "CARDINALITY_REPEATED":
                            self.cardinality = Field_Cardinality(value=3)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.cardinality = Field_Cardinality(value=reader.int32_value())
            elif field_name == "number" or field_name == "number":
                if seen_3:
                    raise Error("proto json: duplicate field number")
                seen_3 = True
                if reader.read_null():
                    self.number = 0
                else:
                    self.number = reader.int32_value()
            elif field_name == "name" or field_name == "name":
                if seen_4:
                    raise Error("proto json: duplicate field name")
                seen_4 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "typeUrl" or field_name == "type_url":
                if seen_6:
                    raise Error("proto json: duplicate field typeUrl")
                seen_6 = True
                if reader.read_null():
                    self.type_url = String()
                else:
                    self.type_url = reader.string_value()
            elif field_name == "oneofIndex" or field_name == "oneof_index":
                if seen_7:
                    raise Error("proto json: duplicate field oneofIndex")
                seen_7 = True
                if reader.read_null():
                    self.oneof_index = 0
                else:
                    self.oneof_index = reader.int32_value()
            elif field_name == "packed" or field_name == "packed":
                if seen_8:
                    raise Error("proto json: duplicate field packed")
                seen_8 = True
                if reader.read_null():
                    self.packed = False
                else:
                    self.packed = reader.bool_value()
            elif field_name == "options" or field_name == "options":
                if seen_9:
                    raise Error("proto json: duplicate field options")
                seen_9 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            elif field_name == "jsonName" or field_name == "json_name":
                if seen_10:
                    raise Error("proto json: duplicate field jsonName")
                seen_10 = True
                if reader.read_null():
                    self.json_name = String()
                else:
                    self.json_name = reader.string_value()
            elif field_name == "defaultValue" or field_name == "default_value":
                if seen_11:
                    raise Error("proto json: duplicate field defaultValue")
                seen_11 = True
                if reader.read_null():
                    self.default_value = String()
                else:
                    self.default_value = reader.string_value()
            else:
                reader.skip_unknown_value()


struct Enum(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Enum` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var enumvalue: List[EnumValue]
    """Field `enumvalue` (number 2, repeated)."""
    var options: List[Option]
    """Field `options` (number 3, repeated)."""
    var source_context: Optional[SourceContext]
    """Field `source_context` (number 4)."""
    var syntax: Syntax
    """Field `syntax` (number 5)."""
    var edition: String
    """Field `edition` (number 6)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.enumvalue = List[EnumValue]()
        self.options = List[Option]()
        self.source_context = None
        self.syntax = Syntax()
        self.edition = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        for v in self.enumvalue:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.source_context:
            var sub = WireWriter()
            self.source_context.value().encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        if self.syntax.value != 0:
            writer.int32(5, self.syntax.value)
        if self.edition.byte_length() != 0:
            writer.string_field(6, self.edition)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = EnumValue()
                    m.merge_from(sub)
                    self.enumvalue.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: SourceContext
                    if self.source_context:
                        m = self.source_context.take()
                    else:
                        m = SourceContext()
                    m.merge_from(sub)
                    self.source_context = m^
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.syntax = Syntax(value=reader.int32_value())
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.edition = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if len(self.enumvalue) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("enumvalue", "enumvalue")
            writer.begin_array()
            for item in self.enumvalue:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if self.source_context:
            writer.field("sourceContext", "source_context")
            writer.message_value(self.source_context.value())
        if self.syntax.value != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("syntax", "syntax")
            if self.syntax.value == 0:
                writer.string_value("SYNTAX_PROTO2")
            elif self.syntax.value == 1:
                writer.string_value("SYNTAX_PROTO3")
            elif self.syntax.value == 2:
                writer.string_value("SYNTAX_EDITIONS")
            else:
                writer.int32_value(self.syntax.value)
        if self.edition.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("edition", "edition")
            writer.string_value(self.edition)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "enumvalue" or field_name == "enumvalue":
                if seen_2:
                    raise Error("proto json: duplicate field enumvalue")
                seen_2 = True
                if reader.read_null():
                    self.enumvalue = List[EnumValue]()
                else:
                    self.enumvalue = List[EnumValue]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.enumvalue.append(reader.message_value[EnumValue]())
            elif field_name == "options" or field_name == "options":
                if seen_3:
                    raise Error("proto json: duplicate field options")
                seen_3 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            elif field_name == "sourceContext" or field_name == "source_context":
                if seen_4:
                    raise Error("proto json: duplicate field sourceContext")
                seen_4 = True
                if reader.read_null():
                    self.source_context = None
                else:
                    self.source_context = reader.message_value[SourceContext]()
            elif field_name == "syntax" or field_name == "syntax":
                if seen_5:
                    raise Error("proto json: duplicate field syntax")
                seen_5 = True
                if reader.read_null():
                    self.syntax = Syntax()
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "SYNTAX_PROTO2":
                            self.syntax = Syntax(value=0)
                        elif enum_name.value() == "SYNTAX_PROTO3":
                            self.syntax = Syntax(value=1)
                        elif enum_name.value() == "SYNTAX_EDITIONS":
                            self.syntax = Syntax(value=2)
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.syntax = Syntax(value=reader.int32_value())
            elif field_name == "edition" or field_name == "edition":
                if seen_6:
                    raise Error("proto json: duplicate field edition")
                seen_6 = True
                if reader.read_null():
                    self.edition = String()
                else:
                    self.edition = reader.string_value()
            else:
                reader.skip_unknown_value()


struct EnumValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EnumValue` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var number: Int32
    """Field `number` (number 2)."""
    var options: List[Option]
    """Field `options` (number 3, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.number = 0
        self.options = List[Option]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.number != 0:
            writer.int32(2, self.number)
        for v in self.options:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.number = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Option()
                    m.merge_from(sub)
                    self.options.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if self.number != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("number", "number")
            writer.int32_value(self.number)
        if len(self.options) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("options", "options")
            writer.begin_array()
            for item in self.options:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "number" or field_name == "number":
                if seen_2:
                    raise Error("proto json: duplicate field number")
                seen_2 = True
                if reader.read_null():
                    self.number = 0
                else:
                    self.number = reader.int32_value()
            elif field_name == "options" or field_name == "options":
                if seen_3:
                    raise Error("proto json: duplicate field options")
                seen_3 = True
                if reader.read_null():
                    self.options = List[Option]()
                else:
                    self.options = List[Option]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.options.append(reader.message_value[Option]())
            else:
                reader.skip_unknown_value()


struct Option(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Option` protobuf message."""

    var name: String
    """Field `name` (number 1)."""
    var value: Optional[Any]
    """Field `value` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.name = String()
        self.value = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.name.byte_length() != 0:
            writer.string_field(1, self.name)
        if self.value:
            var sub = WireWriter()
            self.value.value().encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.name = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Any
                    if self.value:
                        m = self.value.take()
                    else:
                        m = Any()
                    m.merge_from(sub)
                    self.value = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.name.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("name", "name")
            writer.string_value(self.name)
        if self.value:
            writer.field("value", "value")
            writer.message_value(self.value.value())
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "name" or field_name == "name":
                if seen_1:
                    raise Error("proto json: duplicate field name")
                seen_1 = True
                if reader.read_null():
                    self.name = String()
                else:
                    self.name = reader.string_value()
            elif field_name == "value" or field_name == "value":
                if seen_2:
                    raise Error("proto json: duplicate field value")
                seen_2 = True
                if reader.read_null():
                    self.value = None
                else:
                    self.value = reader.message_value[Any]()
            else:
                reader.skip_unknown_value()
