# Generated by protoc-gen-mojo. Do not edit.

"""Static ProtoJSON type resolver for this protoc request."""

from proto import (
    AnyJsonPayload,
    JsonPrintOptions,
    ProtoJsonTypeResolver,
    any_type_name,
    parse_any_json_payload,
    print_any_json_payload,
)
from any_pb import Any as _json_type_0
from api_pb import Api as _json_type_1
from wrappers_pb import BoolValue as _json_type_2
from wrappers_pb import BytesValue as _json_type_3
from wrappers_pb import DoubleValue as _json_type_4
from duration_pb import Duration as _json_type_5
from empty_pb import Empty as _json_type_6
from type_pb import Enum as _json_type_7
from type_pb import EnumValue as _json_type_8
from type_pb import Field as _json_type_9
from field_mask_pb import FieldMask as _json_type_10
from wrappers_pb import FloatValue as _json_type_11
from wrappers_pb import Int32Value as _json_type_12
from wrappers_pb import Int64Value as _json_type_13
from struct_pb import ListValue as _json_type_14
from api_pb import Method as _json_type_15
from api_pb import Mixin as _json_type_16
from type_pb import Option as _json_type_17
from source_context_pb import SourceContext as _json_type_18
from wrappers_pb import StringValue as _json_type_19
from struct_pb import Struct as _json_type_20
from timestamp_pb import Timestamp as _json_type_21
from type_pb import Type as _json_type_22
from wrappers_pb import UInt32Value as _json_type_23
from wrappers_pb import UInt64Value as _json_type_24
from struct_pb import Value as _json_type_25
from vectors_pb import EchoRequest as _json_type_26
from vectors_pb import EchoResponse as _json_type_27
from vectors_pb import EnumValue as _json_type_28
from vectors_pb import JsonAnyParent as _json_type_29
from vectors_pb import JsonAnyPayload as _json_type_30
from vectors_pb import JsonChild as _json_type_31
from vectors_pb import JsonDescriptorMessages as _json_type_32
from vectors_pb import JsonDuration as _json_type_33
from vectors_pb import JsonEmptyParent as _json_type_34
from vectors_pb import JsonFieldMask as _json_type_35
from vectors_pb import JsonKeyMaps as _json_type_36
from vectors_pb import JsonMessageMaps as _json_type_37
from vectors_pb import JsonOneof as _json_type_38
from vectors_pb import JsonOptional as _json_type_39
from vectors_pb import JsonParent as _json_type_40
from vectors_pb import JsonRepeated as _json_type_41
from vectors_pb import JsonRepeatedMessages as _json_type_42
from vectors_pb import JsonStringMaps as _json_type_43
from vectors_pb import JsonStructValues as _json_type_44
from vectors_pb import JsonTimestamp as _json_type_45
from vectors_pb import JsonWrappers as _json_type_46
from vectors_pb import Nested as _json_type_47
from vectors_pb import Scalars as _json_type_48
from vectors_pb import Tree as _json_type_49


def _print_any(
    type_url: String,
    value: List[Byte],
    preserve_proto_field_names: Bool,
    always_print_fields_with_no_presence: Bool,
) raises -> AnyJsonPayload:
    """Resolves one Any wire value to embedded JSON."""
    var type_name = any_type_name(type_url)
    var options = JsonPrintOptions(
        preserve_proto_field_names=preserve_proto_field_names,
        always_print_fields_with_no_presence=(
            always_print_fields_with_no_presence
        ),
        type_resolver=json_type_resolver(),
    )
    if type_name == "google.protobuf.Any":
        return print_any_json_payload[_json_type_0](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Api":
        return print_any_json_payload[_json_type_1](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.BoolValue":
        return print_any_json_payload[_json_type_2](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.BytesValue":
        return print_any_json_payload[_json_type_3](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.DoubleValue":
        return print_any_json_payload[_json_type_4](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Duration":
        return print_any_json_payload[_json_type_5](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Empty":
        return print_any_json_payload[_json_type_6](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Enum":
        return print_any_json_payload[_json_type_7](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.EnumValue":
        return print_any_json_payload[_json_type_8](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Field":
        return print_any_json_payload[_json_type_9](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.FieldMask":
        return print_any_json_payload[_json_type_10](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.FloatValue":
        return print_any_json_payload[_json_type_11](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Int32Value":
        return print_any_json_payload[_json_type_12](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Int64Value":
        return print_any_json_payload[_json_type_13](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.ListValue":
        return print_any_json_payload[_json_type_14](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Method":
        return print_any_json_payload[_json_type_15](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Mixin":
        return print_any_json_payload[_json_type_16](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Option":
        return print_any_json_payload[_json_type_17](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.SourceContext":
        return print_any_json_payload[_json_type_18](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.StringValue":
        return print_any_json_payload[_json_type_19](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Struct":
        return print_any_json_payload[_json_type_20](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Timestamp":
        return print_any_json_payload[_json_type_21](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Type":
        return print_any_json_payload[_json_type_22](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.UInt32Value":
        return print_any_json_payload[_json_type_23](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.UInt64Value":
        return print_any_json_payload[_json_type_24](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Value":
        return print_any_json_payload[_json_type_25](
            value,
            options,
            uses_value_field=True,
        )
    elif type_name == "grpcmojo.test.EchoRequest":
        return print_any_json_payload[_json_type_26](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.EchoResponse":
        return print_any_json_payload[_json_type_27](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.EnumValue":
        return print_any_json_payload[_json_type_28](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonAnyParent":
        return print_any_json_payload[_json_type_29](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonAnyPayload":
        return print_any_json_payload[_json_type_30](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonChild":
        return print_any_json_payload[_json_type_31](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonDescriptorMessages":
        return print_any_json_payload[_json_type_32](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonDuration":
        return print_any_json_payload[_json_type_33](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonEmptyParent":
        return print_any_json_payload[_json_type_34](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonFieldMask":
        return print_any_json_payload[_json_type_35](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonKeyMaps":
        return print_any_json_payload[_json_type_36](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonMessageMaps":
        return print_any_json_payload[_json_type_37](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonOneof":
        return print_any_json_payload[_json_type_38](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonOptional":
        return print_any_json_payload[_json_type_39](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonParent":
        return print_any_json_payload[_json_type_40](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonRepeated":
        return print_any_json_payload[_json_type_41](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonRepeatedMessages":
        return print_any_json_payload[_json_type_42](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonStringMaps":
        return print_any_json_payload[_json_type_43](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonStructValues":
        return print_any_json_payload[_json_type_44](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonTimestamp":
        return print_any_json_payload[_json_type_45](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonWrappers":
        return print_any_json_payload[_json_type_46](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Nested":
        return print_any_json_payload[_json_type_47](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Scalars":
        return print_any_json_payload[_json_type_48](
            value,
            options,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Tree":
        return print_any_json_payload[_json_type_49](
            value,
            options,
            uses_value_field=False,
        )
    raise Error("proto json: unresolved Any type URL")


def _parse_any(
    type_url: String,
    text: String,
    ignore_unknown_fields: Bool,
    max_depth: Int,
) raises -> List[Byte]:
    """Resolves one Any JSON object to embedded wire bytes."""
    var type_name = any_type_name(type_url)
    if type_name == "google.protobuf.Any":
        return parse_any_json_payload[_json_type_0](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Api":
        return parse_any_json_payload[_json_type_1](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.BoolValue":
        return parse_any_json_payload[_json_type_2](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.BytesValue":
        return parse_any_json_payload[_json_type_3](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.DoubleValue":
        return parse_any_json_payload[_json_type_4](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Duration":
        return parse_any_json_payload[_json_type_5](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Empty":
        return parse_any_json_payload[_json_type_6](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Enum":
        return parse_any_json_payload[_json_type_7](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.EnumValue":
        return parse_any_json_payload[_json_type_8](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Field":
        return parse_any_json_payload[_json_type_9](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.FieldMask":
        return parse_any_json_payload[_json_type_10](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.FloatValue":
        return parse_any_json_payload[_json_type_11](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Int32Value":
        return parse_any_json_payload[_json_type_12](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Int64Value":
        return parse_any_json_payload[_json_type_13](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.ListValue":
        return parse_any_json_payload[_json_type_14](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Method":
        return parse_any_json_payload[_json_type_15](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Mixin":
        return parse_any_json_payload[_json_type_16](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.Option":
        return parse_any_json_payload[_json_type_17](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.SourceContext":
        return parse_any_json_payload[_json_type_18](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.StringValue":
        return parse_any_json_payload[_json_type_19](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Struct":
        return parse_any_json_payload[_json_type_20](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Timestamp":
        return parse_any_json_payload[_json_type_21](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Type":
        return parse_any_json_payload[_json_type_22](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "google.protobuf.UInt32Value":
        return parse_any_json_payload[_json_type_23](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.UInt64Value":
        return parse_any_json_payload[_json_type_24](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "google.protobuf.Value":
        return parse_any_json_payload[_json_type_25](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=True,
        )
    elif type_name == "grpcmojo.test.EchoRequest":
        return parse_any_json_payload[_json_type_26](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.EchoResponse":
        return parse_any_json_payload[_json_type_27](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.EnumValue":
        return parse_any_json_payload[_json_type_28](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonAnyParent":
        return parse_any_json_payload[_json_type_29](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonAnyPayload":
        return parse_any_json_payload[_json_type_30](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonChild":
        return parse_any_json_payload[_json_type_31](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonDescriptorMessages":
        return parse_any_json_payload[_json_type_32](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonDuration":
        return parse_any_json_payload[_json_type_33](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonEmptyParent":
        return parse_any_json_payload[_json_type_34](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonFieldMask":
        return parse_any_json_payload[_json_type_35](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonKeyMaps":
        return parse_any_json_payload[_json_type_36](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonMessageMaps":
        return parse_any_json_payload[_json_type_37](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonOneof":
        return parse_any_json_payload[_json_type_38](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonOptional":
        return parse_any_json_payload[_json_type_39](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonParent":
        return parse_any_json_payload[_json_type_40](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonRepeated":
        return parse_any_json_payload[_json_type_41](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonRepeatedMessages":
        return parse_any_json_payload[_json_type_42](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonStringMaps":
        return parse_any_json_payload[_json_type_43](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonStructValues":
        return parse_any_json_payload[_json_type_44](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonTimestamp":
        return parse_any_json_payload[_json_type_45](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.JsonWrappers":
        return parse_any_json_payload[_json_type_46](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Nested":
        return parse_any_json_payload[_json_type_47](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Scalars":
        return parse_any_json_payload[_json_type_48](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    elif type_name == "grpcmojo.test.Tree":
        return parse_any_json_payload[_json_type_49](
            text,
            type_url,
            json_type_resolver(),
            ignore_unknown_fields,
            max_depth,
            uses_value_field=False,
        )
    raise Error("proto json: unresolved Any type URL")


def json_type_resolver() -> ProtoJsonTypeResolver:
    """Returns the static resolver for this generated type set."""
    return ProtoJsonTypeResolver(_print_any, _parse_any)
