# Generated by protoc-gen-mojo from vectors.proto. Do not edit.

"""Generated protobuf messages from `vectors.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct Status:
    """Values of the `Status` protobuf enum (fields carry `Int32`)."""

    comptime STATUS_UNSPECIFIED = 0
    """`STATUS_UNSPECIFIED` = 0."""
    comptime STATUS_ACTIVE = 1
    """`STATUS_ACTIVE` = 1."""
    comptime STATUS_ENABLED = 1
    """`STATUS_ENABLED` = 1."""
    comptime STATUS_PAUSED = 2
    """`STATUS_PAUSED` = 2."""
    comptime STATUS_NEGATIVE = -1
    """`STATUS_NEGATIVE` = -1."""


struct Scalars(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Scalars` protobuf message."""

    var f_int32: Int32
    """Field `f_int32` (number 1)."""
    var f_int64: Int64
    """Field `f_int64` (number 2)."""
    var f_uint32: UInt32
    """Field `f_uint32` (number 3)."""
    var f_uint64: UInt64
    """Field `f_uint64` (number 4)."""
    var f_sint32: Int32
    """Field `f_sint32` (number 5)."""
    var f_sint64: Int64
    """Field `f_sint64` (number 6)."""
    var f_bool: Bool
    """Field `f_bool` (number 7)."""
    var f_fixed32: UInt32
    """Field `f_fixed32` (number 8)."""
    var f_fixed64: UInt64
    """Field `f_fixed64` (number 9)."""
    var f_sfixed32: Int32
    """Field `f_sfixed32` (number 10)."""
    var f_sfixed64: Int64
    """Field `f_sfixed64` (number 11)."""
    var f_float: Float32
    """Field `f_float` (number 12)."""
    var f_double: Float64
    """Field `f_double` (number 13)."""
    var f_string: String
    """Field `f_string` (number 14)."""
    var f_bytes: List[Byte]
    """Field `f_bytes` (number 15)."""
    var f_big_field: Int32
    """Field `f_big_field` (number 1000)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.f_int32 = 0
        self.f_int64 = 0
        self.f_uint32 = 0
        self.f_uint64 = 0
        self.f_sint32 = 0
        self.f_sint64 = 0
        self.f_bool = False
        self.f_fixed32 = 0
        self.f_fixed64 = 0
        self.f_sfixed32 = 0
        self.f_sfixed64 = 0
        self.f_float = 0.0
        self.f_double = 0.0
        self.f_string = String()
        self.f_bytes = List[Byte]()
        self.f_big_field = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.f_int32 != 0:
            writer.int32(1, self.f_int32)
        if self.f_int64 != 0:
            writer.int64(2, self.f_int64)
        if self.f_uint32 != 0:
            writer.uint32(3, self.f_uint32)
        if self.f_uint64 != 0:
            writer.uint64(4, self.f_uint64)
        if self.f_sint32 != 0:
            writer.sint32(5, self.f_sint32)
        if self.f_sint64 != 0:
            writer.sint64(6, self.f_sint64)
        if self.f_bool:
            writer.bool_field(7, self.f_bool)
        if self.f_fixed32 != 0:
            writer.fixed32_field(8, self.f_fixed32)
        if self.f_fixed64 != 0:
            writer.fixed64_field(9, self.f_fixed64)
        if self.f_sfixed32 != 0:
            writer.sfixed32_field(10, self.f_sfixed32)
        if self.f_sfixed64 != 0:
            writer.sfixed64_field(11, self.f_sfixed64)
        if self.f_float != 0.0:
            writer.float_field(12, self.f_float)
        if self.f_double != 0.0:
            writer.double_field(13, self.f_double)
        if self.f_string.byte_length() != 0:
            writer.string_field(14, self.f_string)
        if len(self.f_bytes) != 0:
            writer.bytes_field(15, Span(self.f_bytes))
        if self.f_big_field != 0:
            writer.int32(1000, self.f_big_field)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_int32 = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_int64 = reader.int64_value()
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_uint32 = reader.uint32_value()
            elif field == 4:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_uint64 = reader.varint()
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sint32 = reader.sint32_value()
            elif field == 6:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sint64 = reader.sint64_value()
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_bool = reader.bool_value()
            elif field == 8:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_fixed32 = reader.fixed32()
            elif field == 9:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_fixed64 = reader.fixed64()
            elif field == 10:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sfixed32 = reader.sfixed32_value()
            elif field == 11:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sfixed64 = reader.sfixed64_value()
            elif field == 12:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_float = reader.float_value()
            elif field == 13:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_double = reader.double_value()
            elif field == 14:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_string = reader.string_value()
            elif field == 15:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_bytes = reader.bytes_value()
            elif field == 1000:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_big_field = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.f_int32 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fInt32", "f_int32")
            writer.int32_value(self.f_int32)
        if self.f_int64 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fInt64", "f_int64")
            writer.int64_value(self.f_int64)
        if self.f_uint32 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fUint32", "f_uint32")
            writer.uint32_value(self.f_uint32)
        if self.f_uint64 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fUint64", "f_uint64")
            writer.uint64_value(self.f_uint64)
        if self.f_sint32 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fSint32", "f_sint32")
            writer.int32_value(self.f_sint32)
        if self.f_sint64 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fSint64", "f_sint64")
            writer.int64_value(self.f_sint64)
        if self.f_bool or writer.options.always_print_fields_with_no_presence:
            writer.field("fBool", "f_bool")
            writer.bool_value(self.f_bool)
        if self.f_fixed32 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fFixed32", "f_fixed32")
            writer.uint32_value(self.f_fixed32)
        if self.f_fixed64 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fFixed64", "f_fixed64")
            writer.uint64_value(self.f_fixed64)
        if self.f_sfixed32 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fSfixed32", "f_sfixed32")
            writer.int32_value(self.f_sfixed32)
        if self.f_sfixed64 != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fSfixed64", "f_sfixed64")
            writer.int64_value(self.f_sfixed64)
        if self.f_float != 0.0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fFloat", "f_float")
            writer.float32_value(self.f_float)
        if self.f_double != 0.0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fDouble", "f_double")
            writer.float64_value(self.f_double)
        if self.f_string.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fString", "f_string")
            writer.string_value(self.f_string)
        if len(self.f_bytes) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fBytes", "f_bytes")
            writer.bytes_value(Span(self.f_bytes))
        if self.f_big_field != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fBigField", "f_big_field")
            writer.int32_value(self.f_big_field)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        var seen_7 = False
        var seen_8 = False
        var seen_9 = False
        var seen_10 = False
        var seen_11 = False
        var seen_12 = False
        var seen_13 = False
        var seen_14 = False
        var seen_15 = False
        var seen_1000 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "fInt32" or field_name == "f_int32":
                if seen_1:
                    raise Error("proto json: duplicate field fInt32")
                seen_1 = True
                if reader.read_null():
                    self.f_int32 = 0
                else:
                    self.f_int32 = reader.int32_value()
            elif field_name == "fInt64" or field_name == "f_int64":
                if seen_2:
                    raise Error("proto json: duplicate field fInt64")
                seen_2 = True
                if reader.read_null():
                    self.f_int64 = 0
                else:
                    self.f_int64 = reader.int64_value()
            elif field_name == "fUint32" or field_name == "f_uint32":
                if seen_3:
                    raise Error("proto json: duplicate field fUint32")
                seen_3 = True
                if reader.read_null():
                    self.f_uint32 = 0
                else:
                    self.f_uint32 = reader.uint32_value()
            elif field_name == "fUint64" or field_name == "f_uint64":
                if seen_4:
                    raise Error("proto json: duplicate field fUint64")
                seen_4 = True
                if reader.read_null():
                    self.f_uint64 = 0
                else:
                    self.f_uint64 = reader.uint64_value()
            elif field_name == "fSint32" or field_name == "f_sint32":
                if seen_5:
                    raise Error("proto json: duplicate field fSint32")
                seen_5 = True
                if reader.read_null():
                    self.f_sint32 = 0
                else:
                    self.f_sint32 = reader.int32_value()
            elif field_name == "fSint64" or field_name == "f_sint64":
                if seen_6:
                    raise Error("proto json: duplicate field fSint64")
                seen_6 = True
                if reader.read_null():
                    self.f_sint64 = 0
                else:
                    self.f_sint64 = reader.int64_value()
            elif field_name == "fBool" or field_name == "f_bool":
                if seen_7:
                    raise Error("proto json: duplicate field fBool")
                seen_7 = True
                if reader.read_null():
                    self.f_bool = False
                else:
                    self.f_bool = reader.bool_value()
            elif field_name == "fFixed32" or field_name == "f_fixed32":
                if seen_8:
                    raise Error("proto json: duplicate field fFixed32")
                seen_8 = True
                if reader.read_null():
                    self.f_fixed32 = 0
                else:
                    self.f_fixed32 = reader.uint32_value()
            elif field_name == "fFixed64" or field_name == "f_fixed64":
                if seen_9:
                    raise Error("proto json: duplicate field fFixed64")
                seen_9 = True
                if reader.read_null():
                    self.f_fixed64 = 0
                else:
                    self.f_fixed64 = reader.uint64_value()
            elif field_name == "fSfixed32" or field_name == "f_sfixed32":
                if seen_10:
                    raise Error("proto json: duplicate field fSfixed32")
                seen_10 = True
                if reader.read_null():
                    self.f_sfixed32 = 0
                else:
                    self.f_sfixed32 = reader.int32_value()
            elif field_name == "fSfixed64" or field_name == "f_sfixed64":
                if seen_11:
                    raise Error("proto json: duplicate field fSfixed64")
                seen_11 = True
                if reader.read_null():
                    self.f_sfixed64 = 0
                else:
                    self.f_sfixed64 = reader.int64_value()
            elif field_name == "fFloat" or field_name == "f_float":
                if seen_12:
                    raise Error("proto json: duplicate field fFloat")
                seen_12 = True
                if reader.read_null():
                    self.f_float = 0.0
                else:
                    self.f_float = reader.float32_value()
            elif field_name == "fDouble" or field_name == "f_double":
                if seen_13:
                    raise Error("proto json: duplicate field fDouble")
                seen_13 = True
                if reader.read_null():
                    self.f_double = 0.0
                else:
                    self.f_double = reader.float64_value()
            elif field_name == "fString" or field_name == "f_string":
                if seen_14:
                    raise Error("proto json: duplicate field fString")
                seen_14 = True
                if reader.read_null():
                    self.f_string = String()
                else:
                    self.f_string = reader.string_value()
            elif field_name == "fBytes" or field_name == "f_bytes":
                if seen_15:
                    raise Error("proto json: duplicate field fBytes")
                seen_15 = True
                if reader.read_null():
                    self.f_bytes = List[Byte]()
                else:
                    self.f_bytes = reader.bytes_value()
            elif field_name == "fBigField" or field_name == "f_big_field":
                if seen_1000:
                    raise Error("proto json: duplicate field fBigField")
                seen_1000 = True
                if reader.read_null():
                    self.f_big_field = 0
                else:
                    self.f_big_field = reader.int32_value()
            else:
                reader.skip_unknown_value()


struct Nested(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Nested` protobuf message."""

    var inner: Optional[Scalars]
    """Field `inner` (number 1)."""
    var packed_ints: List[Int32]
    """Field `packed_ints` (number 2, repeated)."""
    var names: List[String]
    """Field `names` (number 3, repeated)."""
    var inners: List[Scalars]
    """Field `inners` (number 4, repeated)."""
    var counts: Dict[String, Int32]
    """Field `counts` (number 5, map field)."""
    var as_text: String
    """Field `as_text` (number 6)."""
    var as_num: Int64
    """Field `as_num` (number 7)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""
    var choice_case: Int
    """Active member of oneof `choice`: 0 when unset, else the set field number."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.inner = None
        self.packed_ints = List[Int32]()
        self.names = List[String]()
        self.inners = List[Scalars]()
        self.counts = Dict[String, Int32]()
        self.as_text = String()
        self.as_num = 0
        self._unknown = List[Byte]()
        self.choice_case = 0

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.inner:
            var sub = WireWriter()
            self.inner.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if len(self.packed_ints) != 0:
            var sub = WireWriter()
            for v in self.packed_ints:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.names:
            writer.string_field(3, v)
        for v in self.inners:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        for entry in self.counts.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(5, Span(sub.buf))
        if self.choice_case == 6:
            writer.string_field(6, self.as_text)
        elif self.choice_case == 7:
            writer.int64(7, self.as_num)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Scalars
                    if self.inner:
                        m = self.inner.take()
                    else:
                        m = Scalars()
                    m.merge_from(sub)
                    self.inner = m^
            elif field == 2:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.packed_ints.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.packed_ints.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.names.append(reader.string_value())
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Scalars()
                    m.merge_from(sub)
                    self.inners.append(m^)
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var entry_start = reader.pos
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    var entry_unknown = False
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1 and etag[1] == WIRE_LEN:
                            key = sub.string_value()
                        elif etag[0] == 2 and etag[1] == WIRE_VARINT:
                            value = sub.int32_value()
                        else:
                            entry_unknown = True
                            sub.skip(etag[1])
                    if entry_unknown:
                        reader.pos = entry_start
                        reader.capture_field(field, wire_type, self._unknown)
                    else:
                        self.counts[key^] = value
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.as_text = reader.string_value()
                    self.choice_case = 6
                    self.as_num = 0
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.as_num = reader.int64_value()
                    self.choice_case = 7
                    self.as_text = String()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Tree(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Tree` protobuf message."""

    var child: List[Tree]
    """Field `child` (number 1, recursive: boxed as a 0-or-1 list)."""
    var v: Int32
    """Field `v` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.child = List[Tree]()
        self.v = 0
        self._unknown = List[Byte]()

    def __deinit__(deinit self):
        """Destroys the message (explicit: breaks the trait-synthesis cycle for recursive types)."""
        pass

    def __init__(out self, *, copy: Self):
        """Deep-copies another message.

        Args:
            copy: The message to copy from.
        """
        self.child = copy.child.copy()
        self.v = copy.v
        self._unknown = copy._unknown.copy()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if len(self.child) != 0:
            var sub = WireWriter()
            self.child[0].encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.v != 0:
            writer.int32(2, self.v)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Tree
                    if len(self.child) != 0:
                        m = self.child.pop()
                    else:
                        m = Tree()
                    m.merge_from(sub)
                    self.child.append(m^)
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.v = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct EchoRequest(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EchoRequest` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.message.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("message", "message")
            writer.string_value(self.message)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "message" or field_name == "message":
                if seen_1:
                    raise Error("proto json: duplicate field message")
                seen_1 = True
                if reader.read_null():
                    self.message = String()
                else:
                    self.message = reader.string_value()
            else:
                reader.skip_unknown_value()


struct EchoResponse(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EchoResponse` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.message.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("message", "message")
            writer.string_value(self.message)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "message" or field_name == "message":
                if seen_1:
                    raise Error("proto json: duplicate field message")
                seen_1 = True
                if reader.read_null():
                    self.message = String()
                else:
                    self.message = reader.string_value()
            else:
                reader.skip_unknown_value()


struct EnumValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EnumValue` protobuf message."""

    var status: Int32
    """Field `status` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.status = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.status != 0:
            writer.int32(1, self.status)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.status = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.status != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("status", "status")
            if self.status == 0:
                writer.string_value("STATUS_UNSPECIFIED")
            elif self.status == 1:
                writer.string_value("STATUS_ACTIVE")
            elif self.status == 2:
                writer.string_value("STATUS_PAUSED")
            elif self.status == -1:
                writer.string_value("STATUS_NEGATIVE")
            else:
                writer.int32_value(self.status)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "status" or field_name == "status":
                if seen_1:
                    raise Error("proto json: duplicate field status")
                seen_1 = True
                if reader.read_null():
                    self.status = 0
                else:
                    var enum_name = reader.enum_name()
                    if enum_name:
                        if enum_name.value() == "STATUS_UNSPECIFIED":
                            self.status = 0
                        elif enum_name.value() == "STATUS_ACTIVE":
                            self.status = 1
                        elif enum_name.value() == "STATUS_ENABLED":
                            self.status = 1
                        elif enum_name.value() == "STATUS_PAUSED":
                            self.status = 2
                        elif enum_name.value() == "STATUS_NEGATIVE":
                            self.status = -1
                        elif not reader.options.ignore_unknown_fields:
                            raise Error("proto json: unknown enum value")
                    else:
                        self.status = reader.int32_value()
            else:
                reader.skip_unknown_value()


struct JsonChild(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `JsonChild` protobuf message."""

    var id: Int32
    """Field `id` (number 1)."""
    var note: String
    """Field `note` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.id = 0
        self.note = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.id != 0:
            writer.int32(1, self.id)
        if self.note.byte_length() != 0:
            writer.string_field(2, self.note)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.id = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.note = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.id != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("id", "id")
            writer.int32_value(self.id)
        if self.note.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("note", "note")
            writer.string_value(self.note)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "id" or field_name == "id":
                if seen_1:
                    raise Error("proto json: duplicate field id")
                seen_1 = True
                if reader.read_null():
                    self.id = 0
                else:
                    self.id = reader.int32_value()
            elif field_name == "note" or field_name == "note":
                if seen_2:
                    raise Error("proto json: duplicate field note")
                seen_2 = True
                if reader.read_null():
                    self.note = String()
                else:
                    self.note = reader.string_value()
            else:
                reader.skip_unknown_value()


struct JsonParent(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `JsonParent` protobuf message."""

    var child: Optional[JsonChild]
    """Field `child` (number 1)."""
    var echo: Optional[EchoRequest]
    """Field `echo` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.child = None
        self.echo = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.child:
            var sub = WireWriter()
            self.child.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.echo:
            var sub = WireWriter()
            self.echo.value().encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: JsonChild
                    if self.child:
                        m = self.child.take()
                    else:
                        m = JsonChild()
                    m.merge_from(sub)
                    self.child = m^
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: EchoRequest
                    if self.echo:
                        m = self.echo.take()
                    else:
                        m = EchoRequest()
                    m.merge_from(sub)
                    self.echo = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.child:
            writer.field("child", "child")
            writer.message_value(self.child.value())
        if self.echo:
            writer.field("echo", "echo")
            writer.message_value(self.echo.value())
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "child" or field_name == "child":
                if seen_1:
                    raise Error("proto json: duplicate field child")
                seen_1 = True
                if reader.read_null():
                    self.child = None
                else:
                    self.child = reader.message_value[JsonChild]()
            elif field_name == "echo" or field_name == "echo":
                if seen_2:
                    raise Error("proto json: duplicate field echo")
                seen_2 = True
                if reader.read_null():
                    self.echo = None
                else:
                    self.echo = reader.message_value[EchoRequest]()
            else:
                reader.skip_unknown_value()


struct JsonRepeated(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `JsonRepeated` protobuf message."""

    var int32_values: List[Int32]
    """Field `int32_values` (number 1, repeated)."""
    var int64_values: List[Int64]
    """Field `int64_values` (number 2, repeated)."""
    var uint32_values: List[UInt32]
    """Field `uint32_values` (number 3, repeated)."""
    var uint64_values: List[UInt64]
    """Field `uint64_values` (number 4, repeated)."""
    var sint32_values: List[Int32]
    """Field `sint32_values` (number 5, repeated)."""
    var sint64_values: List[Int64]
    """Field `sint64_values` (number 6, repeated)."""
    var bool_values: List[Bool]
    """Field `bool_values` (number 7, repeated)."""
    var fixed32_values: List[UInt32]
    """Field `fixed32_values` (number 8, repeated)."""
    var fixed64_values: List[UInt64]
    """Field `fixed64_values` (number 9, repeated)."""
    var sfixed32_values: List[Int32]
    """Field `sfixed32_values` (number 10, repeated)."""
    var sfixed64_values: List[Int64]
    """Field `sfixed64_values` (number 11, repeated)."""
    var float_values: List[Float32]
    """Field `float_values` (number 12, repeated)."""
    var double_values: List[Float64]
    """Field `double_values` (number 13, repeated)."""
    var string_values: List[String]
    """Field `string_values` (number 14, repeated)."""
    var bytes_values: List[List[Byte]]
    """Field `bytes_values` (number 15, repeated)."""
    var status_values: List[Int32]
    """Field `status_values` (number 16, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.int32_values = List[Int32]()
        self.int64_values = List[Int64]()
        self.uint32_values = List[UInt32]()
        self.uint64_values = List[UInt64]()
        self.sint32_values = List[Int32]()
        self.sint64_values = List[Int64]()
        self.bool_values = List[Bool]()
        self.fixed32_values = List[UInt32]()
        self.fixed64_values = List[UInt64]()
        self.sfixed32_values = List[Int32]()
        self.sfixed64_values = List[Int64]()
        self.float_values = List[Float32]()
        self.double_values = List[Float64]()
        self.string_values = List[String]()
        self.bytes_values = List[List[Byte]]()
        self.status_values = List[Int32]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if len(self.int32_values) != 0:
            var sub = WireWriter()
            for v in self.int32_values:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(1, Span(sub.buf))
        if len(self.int64_values) != 0:
            var sub = WireWriter()
            for v in self.int64_values:
                sub.varint(UInt64(v))
            writer.len_prefixed(2, Span(sub.buf))
        if len(self.uint32_values) != 0:
            var sub = WireWriter()
            for v in self.uint32_values:
                sub.varint(UInt64(v))
            writer.len_prefixed(3, Span(sub.buf))
        if len(self.uint64_values) != 0:
            var sub = WireWriter()
            for v in self.uint64_values:
                sub.varint(v)
            writer.len_prefixed(4, Span(sub.buf))
        if len(self.sint32_values) != 0:
            var sub = WireWriter()
            for v in self.sint32_values:
                sub.varint(zigzag_encode64(Int64(v)))
            writer.len_prefixed(5, Span(sub.buf))
        if len(self.sint64_values) != 0:
            var sub = WireWriter()
            for v in self.sint64_values:
                sub.varint(zigzag_encode64(v))
            writer.len_prefixed(6, Span(sub.buf))
        if len(self.bool_values) != 0:
            var sub = WireWriter()
            for v in self.bool_values:
                sub.varint(UInt64(1) if v else UInt64(0))
            writer.len_prefixed(7, Span(sub.buf))
        if len(self.fixed32_values) != 0:
            var sub = WireWriter()
            for v in self.fixed32_values:
                sub.fixed32(v)
            writer.len_prefixed(8, Span(sub.buf))
        if len(self.fixed64_values) != 0:
            var sub = WireWriter()
            for v in self.fixed64_values:
                sub.fixed64(v)
            writer.len_prefixed(9, Span(sub.buf))
        if len(self.sfixed32_values) != 0:
            var sub = WireWriter()
            for v in self.sfixed32_values:
                sub.fixed32(UInt32(from_bits=v))
            writer.len_prefixed(10, Span(sub.buf))
        if len(self.sfixed64_values) != 0:
            var sub = WireWriter()
            for v in self.sfixed64_values:
                sub.fixed64(UInt64(from_bits=v))
            writer.len_prefixed(11, Span(sub.buf))
        if len(self.float_values) != 0:
            var sub = WireWriter()
            for v in self.float_values:
                sub.fixed32(UInt32(v.to_bits()))
            writer.len_prefixed(12, Span(sub.buf))
        if len(self.double_values) != 0:
            var sub = WireWriter()
            for v in self.double_values:
                sub.fixed64(UInt64(v.to_bits()))
            writer.len_prefixed(13, Span(sub.buf))
        for v in self.string_values:
            writer.string_field(14, v)
        for v in self.bytes_values:
            writer.bytes_field(15, Span(v))
        if len(self.status_values) != 0:
            var sub = WireWriter()
            for v in self.status_values:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(16, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.int32_values.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.int32_values.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 2:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.int64_values.append(sub.int64_value())
                elif wire_type == WIRE_VARINT:
                    self.int64_values.append(reader.int64_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 3:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.uint32_values.append(sub.uint32_value())
                elif wire_type == WIRE_VARINT:
                    self.uint32_values.append(reader.uint32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 4:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.uint64_values.append(sub.varint())
                elif wire_type == WIRE_VARINT:
                    self.uint64_values.append(reader.varint())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 5:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.sint32_values.append(sub.sint32_value())
                elif wire_type == WIRE_VARINT:
                    self.sint32_values.append(reader.sint32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 6:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.sint64_values.append(sub.sint64_value())
                elif wire_type == WIRE_VARINT:
                    self.sint64_values.append(reader.sint64_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 7:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.bool_values.append(sub.bool_value())
                elif wire_type == WIRE_VARINT:
                    self.bool_values.append(reader.bool_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 8:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.fixed32_values.append(sub.fixed32())
                elif wire_type == WIRE_FIXED32:
                    self.fixed32_values.append(reader.fixed32())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 9:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.fixed64_values.append(sub.fixed64())
                elif wire_type == WIRE_FIXED64:
                    self.fixed64_values.append(reader.fixed64())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 10:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.sfixed32_values.append(sub.sfixed32_value())
                elif wire_type == WIRE_FIXED32:
                    self.sfixed32_values.append(reader.sfixed32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 11:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.sfixed64_values.append(sub.sfixed64_value())
                elif wire_type == WIRE_FIXED64:
                    self.sfixed64_values.append(reader.sfixed64_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 12:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.float_values.append(sub.float_value())
                elif wire_type == WIRE_FIXED32:
                    self.float_values.append(reader.float_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 13:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.double_values.append(sub.double_value())
                elif wire_type == WIRE_FIXED64:
                    self.double_values.append(reader.double_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 14:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.string_values.append(reader.string_value())
            elif field == 15:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.bytes_values.append(reader.bytes_value())
            elif field == 16:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.status_values.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.status_values.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if len(self.int32_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("int32Values", "int32_values")
            writer.begin_array()
            for item in self.int32_values:
                writer.array_item()
                writer.int32_value(item)
            writer.end_array()
        if len(self.int64_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("int64Values", "int64_values")
            writer.begin_array()
            for item in self.int64_values:
                writer.array_item()
                writer.int64_value(item)
            writer.end_array()
        if len(self.uint32_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("uint32Values", "uint32_values")
            writer.begin_array()
            for item in self.uint32_values:
                writer.array_item()
                writer.uint32_value(item)
            writer.end_array()
        if len(self.uint64_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("uint64Values", "uint64_values")
            writer.begin_array()
            for item in self.uint64_values:
                writer.array_item()
                writer.uint64_value(item)
            writer.end_array()
        if len(self.sint32_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("sint32Values", "sint32_values")
            writer.begin_array()
            for item in self.sint32_values:
                writer.array_item()
                writer.int32_value(item)
            writer.end_array()
        if len(self.sint64_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("sint64Values", "sint64_values")
            writer.begin_array()
            for item in self.sint64_values:
                writer.array_item()
                writer.int64_value(item)
            writer.end_array()
        if len(self.bool_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("boolValues", "bool_values")
            writer.begin_array()
            for item in self.bool_values:
                writer.array_item()
                writer.bool_value(item)
            writer.end_array()
        if len(self.fixed32_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fixed32Values", "fixed32_values")
            writer.begin_array()
            for item in self.fixed32_values:
                writer.array_item()
                writer.uint32_value(item)
            writer.end_array()
        if len(self.fixed64_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("fixed64Values", "fixed64_values")
            writer.begin_array()
            for item in self.fixed64_values:
                writer.array_item()
                writer.uint64_value(item)
            writer.end_array()
        if len(self.sfixed32_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("sfixed32Values", "sfixed32_values")
            writer.begin_array()
            for item in self.sfixed32_values:
                writer.array_item()
                writer.int32_value(item)
            writer.end_array()
        if len(self.sfixed64_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("sfixed64Values", "sfixed64_values")
            writer.begin_array()
            for item in self.sfixed64_values:
                writer.array_item()
                writer.int64_value(item)
            writer.end_array()
        if len(self.float_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("floatValues", "float_values")
            writer.begin_array()
            for item in self.float_values:
                writer.array_item()
                writer.float32_value(item)
            writer.end_array()
        if len(self.double_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("doubleValues", "double_values")
            writer.begin_array()
            for item in self.double_values:
                writer.array_item()
                writer.float64_value(item)
            writer.end_array()
        if len(self.string_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("stringValues", "string_values")
            writer.begin_array()
            for item in self.string_values:
                writer.array_item()
                writer.string_value(item)
            writer.end_array()
        if len(self.bytes_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("bytesValues", "bytes_values")
            writer.begin_array()
            for item in self.bytes_values:
                writer.array_item()
                writer.bytes_value(Span(item))
            writer.end_array()
        if len(self.status_values) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("statusValues", "status_values")
            writer.begin_array()
            for item in self.status_values:
                writer.array_item()
                if item == 0:
                    writer.string_value("STATUS_UNSPECIFIED")
                elif item == 1:
                    writer.string_value("STATUS_ACTIVE")
                elif item == 2:
                    writer.string_value("STATUS_PAUSED")
                elif item == -1:
                    writer.string_value("STATUS_NEGATIVE")
                else:
                    writer.int32_value(item)
            writer.end_array()
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        var seen_3 = False
        var seen_4 = False
        var seen_5 = False
        var seen_6 = False
        var seen_7 = False
        var seen_8 = False
        var seen_9 = False
        var seen_10 = False
        var seen_11 = False
        var seen_12 = False
        var seen_13 = False
        var seen_14 = False
        var seen_15 = False
        var seen_16 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "int32Values" or field_name == "int32_values":
                if seen_1:
                    raise Error("proto json: duplicate field int32Values")
                seen_1 = True
                if reader.read_null():
                    self.int32_values = List[Int32]()
                else:
                    self.int32_values = List[Int32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.int32_values.append(reader.int32_value())
            elif field_name == "int64Values" or field_name == "int64_values":
                if seen_2:
                    raise Error("proto json: duplicate field int64Values")
                seen_2 = True
                if reader.read_null():
                    self.int64_values = List[Int64]()
                else:
                    self.int64_values = List[Int64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.int64_values.append(reader.int64_value())
            elif field_name == "uint32Values" or field_name == "uint32_values":
                if seen_3:
                    raise Error("proto json: duplicate field uint32Values")
                seen_3 = True
                if reader.read_null():
                    self.uint32_values = List[UInt32]()
                else:
                    self.uint32_values = List[UInt32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.uint32_values.append(reader.uint32_value())
            elif field_name == "uint64Values" or field_name == "uint64_values":
                if seen_4:
                    raise Error("proto json: duplicate field uint64Values")
                seen_4 = True
                if reader.read_null():
                    self.uint64_values = List[UInt64]()
                else:
                    self.uint64_values = List[UInt64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.uint64_values.append(reader.uint64_value())
            elif field_name == "sint32Values" or field_name == "sint32_values":
                if seen_5:
                    raise Error("proto json: duplicate field sint32Values")
                seen_5 = True
                if reader.read_null():
                    self.sint32_values = List[Int32]()
                else:
                    self.sint32_values = List[Int32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.sint32_values.append(reader.int32_value())
            elif field_name == "sint64Values" or field_name == "sint64_values":
                if seen_6:
                    raise Error("proto json: duplicate field sint64Values")
                seen_6 = True
                if reader.read_null():
                    self.sint64_values = List[Int64]()
                else:
                    self.sint64_values = List[Int64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.sint64_values.append(reader.int64_value())
            elif field_name == "boolValues" or field_name == "bool_values":
                if seen_7:
                    raise Error("proto json: duplicate field boolValues")
                seen_7 = True
                if reader.read_null():
                    self.bool_values = List[Bool]()
                else:
                    self.bool_values = List[Bool]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.bool_values.append(reader.bool_value())
            elif field_name == "fixed32Values" or field_name == "fixed32_values":
                if seen_8:
                    raise Error("proto json: duplicate field fixed32Values")
                seen_8 = True
                if reader.read_null():
                    self.fixed32_values = List[UInt32]()
                else:
                    self.fixed32_values = List[UInt32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.fixed32_values.append(reader.uint32_value())
            elif field_name == "fixed64Values" or field_name == "fixed64_values":
                if seen_9:
                    raise Error("proto json: duplicate field fixed64Values")
                seen_9 = True
                if reader.read_null():
                    self.fixed64_values = List[UInt64]()
                else:
                    self.fixed64_values = List[UInt64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.fixed64_values.append(reader.uint64_value())
            elif field_name == "sfixed32Values" or field_name == "sfixed32_values":
                if seen_10:
                    raise Error("proto json: duplicate field sfixed32Values")
                seen_10 = True
                if reader.read_null():
                    self.sfixed32_values = List[Int32]()
                else:
                    self.sfixed32_values = List[Int32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.sfixed32_values.append(reader.int32_value())
            elif field_name == "sfixed64Values" or field_name == "sfixed64_values":
                if seen_11:
                    raise Error("proto json: duplicate field sfixed64Values")
                seen_11 = True
                if reader.read_null():
                    self.sfixed64_values = List[Int64]()
                else:
                    self.sfixed64_values = List[Int64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.sfixed64_values.append(reader.int64_value())
            elif field_name == "floatValues" or field_name == "float_values":
                if seen_12:
                    raise Error("proto json: duplicate field floatValues")
                seen_12 = True
                if reader.read_null():
                    self.float_values = List[Float32]()
                else:
                    self.float_values = List[Float32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.float_values.append(reader.float32_value())
            elif field_name == "doubleValues" or field_name == "double_values":
                if seen_13:
                    raise Error("proto json: duplicate field doubleValues")
                seen_13 = True
                if reader.read_null():
                    self.double_values = List[Float64]()
                else:
                    self.double_values = List[Float64]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.double_values.append(reader.float64_value())
            elif field_name == "stringValues" or field_name == "string_values":
                if seen_14:
                    raise Error("proto json: duplicate field stringValues")
                seen_14 = True
                if reader.read_null():
                    self.string_values = List[String]()
                else:
                    self.string_values = List[String]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.string_values.append(reader.string_value())
            elif field_name == "bytesValues" or field_name == "bytes_values":
                if seen_15:
                    raise Error("proto json: duplicate field bytesValues")
                seen_15 = True
                if reader.read_null():
                    self.bytes_values = List[List[Byte]]()
                else:
                    self.bytes_values = List[List[Byte]]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.bytes_values.append(reader.bytes_value())
            elif field_name == "statusValues" or field_name == "status_values":
                if seen_16:
                    raise Error("proto json: duplicate field statusValues")
                seen_16 = True
                if reader.read_null():
                    self.status_values = List[Int32]()
                else:
                    self.status_values = List[Int32]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        var enum_name = reader.enum_name()
                        if enum_name:
                            if enum_name.value() == "STATUS_UNSPECIFIED":
                                self.status_values.append(0)
                            elif enum_name.value() == "STATUS_ACTIVE":
                                self.status_values.append(1)
                            elif enum_name.value() == "STATUS_ENABLED":
                                self.status_values.append(1)
                            elif enum_name.value() == "STATUS_PAUSED":
                                self.status_values.append(2)
                            elif enum_name.value() == "STATUS_NEGATIVE":
                                self.status_values.append(-1)
                            elif not reader.options.ignore_unknown_fields:
                                raise Error("proto json: unknown enum value")
                        else:
                            self.status_values.append(reader.int32_value())
            else:
                reader.skip_unknown_value()


struct JsonRepeatedMessages(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `JsonRepeatedMessages` protobuf message."""

    var children: List[JsonChild]
    """Field `children` (number 1, repeated)."""
    var echoes: List[EchoRequest]
    """Field `echoes` (number 2, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.children = List[JsonChild]()
        self.echoes = List[EchoRequest]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for v in self.children:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        for v in self.echoes:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = JsonChild()
                    m.merge_from(sub)
                    self.children.append(m^)
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = EchoRequest()
                    m.merge_from(sub)
                    self.echoes.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if len(self.children) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("children", "children")
            writer.begin_array()
            for item in self.children:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        if len(self.echoes) != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("echoes", "echoes")
            writer.begin_array()
            for item in self.echoes:
                writer.array_item()
                writer.message_value(item)
            writer.end_array()
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        var seen_2 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "children" or field_name == "children":
                if seen_1:
                    raise Error("proto json: duplicate field children")
                seen_1 = True
                if reader.read_null():
                    self.children = List[JsonChild]()
                else:
                    self.children = List[JsonChild]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.children.append(reader.message_value[JsonChild]())
            elif field_name == "echoes" or field_name == "echoes":
                if seen_2:
                    raise Error("proto json: duplicate field echoes")
                seen_2 = True
                if reader.read_null():
                    self.echoes = List[EchoRequest]()
                else:
                    self.echoes = List[EchoRequest]()
                    reader.begin_array()
                    while reader.next_array_item():
                        if reader.read_null():
                            raise Error("proto json: null array element")
                        self.echoes.append(reader.message_value[EchoRequest]())
            else:
                reader.skip_unknown_value()
