# GENERATED by protoc-gen-mojo from vectors.proto — do not edit.

"""Generated protobuf messages from `vectors.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)


struct Scalars(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Scalars` protobuf message."""

    var f_int32: Int32
    """Field `f_int32` (number 1)."""
    var f_int64: Int64
    """Field `f_int64` (number 2)."""
    var f_uint32: UInt32
    """Field `f_uint32` (number 3)."""
    var f_uint64: UInt64
    """Field `f_uint64` (number 4)."""
    var f_sint32: Int32
    """Field `f_sint32` (number 5)."""
    var f_sint64: Int64
    """Field `f_sint64` (number 6)."""
    var f_bool: Bool
    """Field `f_bool` (number 7)."""
    var f_fixed32: UInt32
    """Field `f_fixed32` (number 8)."""
    var f_fixed64: UInt64
    """Field `f_fixed64` (number 9)."""
    var f_sfixed32: Int32
    """Field `f_sfixed32` (number 10)."""
    var f_sfixed64: Int64
    """Field `f_sfixed64` (number 11)."""
    var f_float: Float32
    """Field `f_float` (number 12)."""
    var f_double: Float64
    """Field `f_double` (number 13)."""
    var f_string: String
    """Field `f_string` (number 14)."""
    var f_bytes: List[Byte]
    """Field `f_bytes` (number 15)."""
    var f_big_field: Int32
    """Field `f_big_field` (number 1000)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.f_int32 = 0
        self.f_int64 = 0
        self.f_uint32 = 0
        self.f_uint64 = 0
        self.f_sint32 = 0
        self.f_sint64 = 0
        self.f_bool = False
        self.f_fixed32 = 0
        self.f_fixed64 = 0
        self.f_sfixed32 = 0
        self.f_sfixed64 = 0
        self.f_float = 0.0
        self.f_double = 0.0
        self.f_string = String()
        self.f_bytes = List[Byte]()
        self.f_big_field = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.f_int32 != 0:
            writer.int32(1, self.f_int32)
        if self.f_int64 != 0:
            writer.int64(2, self.f_int64)
        if self.f_uint32 != 0:
            writer.uint32(3, self.f_uint32)
        if self.f_uint64 != 0:
            writer.uint64(4, self.f_uint64)
        if self.f_sint32 != 0:
            writer.sint32(5, self.f_sint32)
        if self.f_sint64 != 0:
            writer.sint64(6, self.f_sint64)
        if self.f_bool:
            writer.bool_field(7, self.f_bool)
        if self.f_fixed32 != 0:
            writer.fixed32_field(8, self.f_fixed32)
        if self.f_fixed64 != 0:
            writer.fixed64_field(9, self.f_fixed64)
        if self.f_sfixed32 != 0:
            writer.sfixed32_field(10, self.f_sfixed32)
        if self.f_sfixed64 != 0:
            writer.sfixed64_field(11, self.f_sfixed64)
        if self.f_float != 0.0:
            writer.float_field(12, self.f_float)
        if self.f_double != 0.0:
            writer.double_field(13, self.f_double)
        if self.f_string.byte_length() != 0:
            writer.string_field(14, self.f_string)
        if len(self.f_bytes) != 0:
            writer.bytes_field(15, Span(self.f_bytes))
        if self.f_big_field != 0:
            writer.int32(1000, self.f_big_field)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_int32 = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_int64 = reader.int64_value()
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_uint32 = reader.uint32_value()
            elif field == 4:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_uint64 = reader.varint()
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sint32 = reader.sint32_value()
            elif field == 6:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sint64 = reader.sint64_value()
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_bool = reader.bool_value()
            elif field == 8:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_fixed32 = reader.fixed32()
            elif field == 9:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_fixed64 = reader.fixed64()
            elif field == 10:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sfixed32 = reader.sfixed32_value()
            elif field == 11:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_sfixed64 = reader.sfixed64_value()
            elif field == 12:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_float = reader.float_value()
            elif field == 13:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_double = reader.double_value()
            elif field == 14:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_string = reader.string_value()
            elif field == 15:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_bytes = reader.bytes_value()
            elif field == 1000:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.f_big_field = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Nested(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Nested` protobuf message."""

    var inner: Optional[Scalars]
    """Field `inner` (number 1)."""
    var packed_ints: List[Int32]
    """Field `packed_ints` (number 2, repeated)."""
    var names: List[String]
    """Field `names` (number 3, repeated)."""
    var inners: List[Scalars]
    """Field `inners` (number 4, repeated)."""
    var counts: Dict[String, Int32]
    """Field `counts` (number 5, map field)."""
    var as_text: String
    """Field `as_text` (number 6)."""
    var as_num: Int64
    """Field `as_num` (number 7)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""
    var choice_case: Int
    """Active member of oneof `choice`: 0 when unset, else the set field number."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.inner = None
        self.packed_ints = List[Int32]()
        self.names = List[String]()
        self.inners = List[Scalars]()
        self.counts = Dict[String, Int32]()
        self.as_text = String()
        self.as_num = 0
        self._unknown = List[Byte]()
        self.choice_case = 0

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.inner:
            var sub = WireWriter()
            self.inner.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if len(self.packed_ints) != 0:
            var sub = WireWriter()
            for v in self.packed_ints:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(2, Span(sub.buf))
        for v in self.names:
            writer.string_field(3, v)
        for v in self.inners:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        for entry in self.counts.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(5, Span(sub.buf))
        if self.choice_case == 6:
            writer.string_field(6, self.as_text)
        elif self.choice_case == 7:
            writer.int64(7, self.as_num)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Scalars
                    if self.inner:
                        m = self.inner.take()
                    else:
                        m = Scalars()
                    m.merge_from(sub)
                    self.inner = m^
            elif field == 2:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.packed_ints.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.packed_ints.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.names.append(reader.string_value())
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = Scalars()
                    m.merge_from(sub)
                    self.inners.append(m^)
            elif field == 5:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.counts[key^] = value
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.as_text = reader.string_value()
                    self.choice_case = 6
                    self.as_num = 0
            elif field == 7:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.as_num = reader.int64_value()
                    self.choice_case = 7
                    self.as_text = String()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Tree(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Tree` protobuf message."""

    var child: List[Tree]
    """Field `child` (number 1, recursive: boxed as a 0-or-1 list)."""
    var v: Int32
    """Field `v` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.child = List[Tree]()
        self.v = 0
        self._unknown = List[Byte]()

    def __deinit__(deinit self):
        """Destroys the message (explicit: breaks the trait-synthesis cycle for recursive types).
        """
        pass

    def __init__(out self, *, copy: Self):
        """Deep-copies another message.

        Args:
            copy: The message to copy from.
        """
        self.child = copy.child.copy()
        self.v = copy.v
        self._unknown = copy._unknown.copy()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if len(self.child) != 0:
            var sub = WireWriter()
            self.child[0].encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.v != 0:
            writer.int32(2, self.v)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Tree
                    if len(self.child) != 0:
                        m = self.child.pop()
                    else:
                        m = Tree()
                    m.merge_from(sub)
                    self.child.append(m^)
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.v = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct EchoRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `EchoRequest` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct EchoResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `EchoResponse` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)
