# Generated by protoc-gen-mojo from google/protobuf/wrappers.proto. Do not edit.

"""Generated protobuf messages from `google/protobuf/wrappers.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct DoubleValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `DoubleValue` protobuf message."""

    var value: Float64
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0.0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if UInt64(self.value.to_bits()) != 0:
            writer.double_field(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.double_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.float64_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.float64_value()


struct FloatValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `FloatValue` protobuf message."""

    var value: Float32
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0.0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if UInt32(self.value.to_bits()) != 0:
            writer.float_field(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_FIXED32:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.float_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.float32_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.float32_value()


struct Int64Value(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Int64Value` protobuf message."""

    var value: Int64
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value != 0:
            writer.int64(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.int64_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.int64_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.int64_value()


struct UInt64Value(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `UInt64Value` protobuf message."""

    var value: UInt64
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value != 0:
            writer.uint64(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.varint()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.uint64_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.uint64_value()


struct Int32Value(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Int32Value` protobuf message."""

    var value: Int32
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value != 0:
            writer.int32(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.int32_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.int32_value()


struct UInt32Value(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `UInt32Value` protobuf message."""

    var value: UInt32
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value != 0:
            writer.uint32(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.uint32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.uint32_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.uint32_value()


struct BoolValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `BoolValue` protobuf message."""

    var value: Bool
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = False
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value:
            writer.bool_field(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.bool_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.bool_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.bool_value()


struct StringValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `StringValue` protobuf message."""

    var value: String
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value.byte_length() != 0:
            writer.string_field(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.string_value(self.value)

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.string_value()


struct BytesValue(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `BytesValue` protobuf message."""

    var value: List[Byte]
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = List[Byte]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if len(self.value) != 0:
            writer.bytes_field(1, Span(self.value))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.bytes_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this wrapper using its scalar JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If the value cannot be written as valid JSON.
        """
        writer.bytes_value(Span(self.value))

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Reads this wrapper from its scalar JSON mapping.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        self.value = reader.bytes_value()
