# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  review_progress: true
  fail_commit_status: true
  in_progress_fortune: false
  enable_prompt_for_ai_agents: false
  auto_review:
    enabled: true
    drafts: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0
    base_branches:
      - ".*"
