# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026 the grpc-mojo contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
# ===----------------------------------------------------------------------=== #

"""The `ProtoMessage` trait and the generic `encode`/`decode` entry points.

Defines the contract between message types — generated by
`tools/protoc-gen-mojo` or hand-written — and everything built on top of
them (gRPC serialization, tests). A conforming type knows how to write
itself to a `WireWriter` and how to merge decoded fields from a
`WireReader`; `encode` and `decode` wrap those two methods for the common
whole-message case.
"""

from .wire import WireReader, WireWriter


trait ProtoMessage(Defaultable, Deinitable, Movable):
    """A protobuf message that can serialize itself to the wire format.

    Generated code (tools/protoc-gen-mojo) and hand-written messages both
    implement this; everything above (gRPC framing, clients, servers) is
    generic over it.
    """

    def encode_to(self, mut writer: WireWriter):
        """Appends this message's wire-format bytes to the writer.

        Implementations follow proto3 semantics: singular fields at their
        default value are omitted, and preserved unknown-field bytes are
        re-emitted.

        Args:
            writer: The destination for the encoded bytes.
        """
        ...

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Per protobuf merge semantics: later values of singular fields
        overwrite earlier ones, repeated fields append, submessages merge
        recursively, and unknown fields are captured for re-emission.

        Args:
            reader: The wire-format bytes to decode; consumed to the end.

        Raises:
            If the wire data is malformed or exceeds the nesting-depth
            limit.
        """
        ...


def encode[M: ProtoMessage](msg: M) -> List[Byte]:
    """Serializes a message to wire-format bytes.

    Parameters:
        M: The message type (usually inferred from `msg`).

    Args:
        msg: The message to serialize.

    Returns:
        The encoded bytes; empty when every field holds its default value.
    """
    var w = WireWriter()
    msg.encode_to(w)
    return w^.take()


def decode[M: ProtoMessage](data: Span[Byte, _]) raises -> M:
    """Parses a message from wire-format bytes.

    Decodes into a default-constructed message via `merge_from`, so unknown
    fields are preserved and duplicate singular fields follow
    last-value-wins semantics.

    Parameters:
        M: The message type to decode; usually stated explicitly at the
            call site, e.g. `decode[EchoRequest](bytes)`.

    Args:
        data: The wire-format bytes of one complete message.

    Returns:
        The decoded message.

    Raises:
        If the wire data is malformed (truncated values, overlong varints,
        invalid field numbers, group wire types) or nests deeper than
        `MAX_DECODE_DEPTH`.
    """
    var m = M()
    var r = WireReader(data)
    m.merge_from(r)
    return m^
