#!/usr/bin/env python3
"""Generate protobuf golden test vectors for the Mojo `proto` package.

Uses the reference Python protobuf implementation so our wire-format
encoder/decoder is checked against upstream, not against itself.

Writes test/proto/golden_vectors.mojo with hex-string constants.
"""

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # the protomojo package
PROTO_DIR = ROOT / "test"


def compile_proto(tmp: Path):
    subprocess.run(
        [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"-I{PROTO_DIR}",
            f"--python_out={tmp}",
            str(PROTO_DIR / "vectors.proto"),
        ],
        check=True,
    )
    sys.path.insert(0, str(tmp))


def main():
    with tempfile.TemporaryDirectory() as tmp:
        compile_proto(Path(tmp))
        import vectors_pb2 as pb  # noqa: E402

        vectors: list[tuple[str, bytes]] = []

        s = pb.Scalars(
            f_int32=150,
            f_int64=-2,
            f_uint32=300,
            f_uint64=1 << 60,
            f_sint32=-1,
            f_sint64=-(1 << 40),
            f_bool=True,
            f_fixed32=0xDEADBEEF,
            f_fixed64=0x0123456789ABCDEF,
            f_sfixed32=-2,
            f_sfixed64=-3,
            f_float=1.5,
            f_double=-2.25,
            f_string="héllo",
            f_bytes=b"\x00\x01\xff",
            f_big_field=7,
        )
        vectors.append(("SCALARS_FULL", s.SerializeToString()))

        vectors.append(("SCALARS_EMPTY", pb.Scalars().SerializeToString()))

        s2 = pb.Scalars(f_int32=-1)  # negative int32 → 10-byte varint
        vectors.append(("SCALARS_NEG_INT32", s2.SerializeToString()))

        n = pb.Nested(
            inner=pb.Scalars(f_int32=1, f_string="x"),
            packed_ints=[1, 2, 300, -1],
            names=["a", "bb", ""],
            inners=[pb.Scalars(f_bool=True), pb.Scalars()],
            as_text="chosen",
        )
        n.counts["one"] = 1
        n.counts["two"] = 2
        vectors.append(("NESTED_FULL", n.SerializeToString()))

        # Byte-exact encode target: single-entry map (protobuf leaves
        # multi-entry map serialization order unspecified).
        n_enc = pb.Nested(
            inner=pb.Scalars(f_int32=1, f_string="x"),
            packed_ints=[1, 2, 300, -1],
            names=["a", "bb", ""],
            inners=[pb.Scalars(f_bool=True), pb.Scalars()],
            as_text="chosen",
        )
        n_enc.counts["one"] = 1
        vectors.append(("NESTED_ENC", n_enc.SerializeToString()))

        n2 = pb.Nested(as_num=-5)
        vectors.append(("NESTED_ONEOF_NUM", n2.SerializeToString()))

        e = pb.EchoRequest(message="ping")
        vectors.append(("ECHO_PING", e.SerializeToString()))

        out = PROTO_DIR / "proto_golden.mojo"
        lines = [
            "# GENERATED by tools/gen_proto_vectors.py — do not edit.",
            "# Golden bytes from the reference Python protobuf implementation.",
            "",
        ]
        for name, data in vectors:
            lines.append(f'comptime {name} = "{data.hex()}"')
        # Field-presence notes for decoder assertions live in the test file.
        out.write_text("\n".join(lines) + "\n")
        print(f"wrote {out} ({len(vectors)} vectors)")


if __name__ == "__main__":
    main()
